### PR TITLE
fix: Add default CORS options to DIDComm HTTP Transport

### LINKED ISSUE #1244: Add default CORS option to DIDComm HTTP transport
Add default CORS option to Framework provided HTTP transport - https://github.com/hyperledger/aries-framework-go/tree/master/pkg/didcomm/transport/http

### PR DESCRIPTION
**Pull request by rolsonquadras**
closes #1244 

Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

### CODE REVIEW

File: pkg/didcomm/transport/http/inbound.go [hunk 1]
```diff
@@ -33,9 +35,9 @@ func NewInboundHandler(prov transport.Provider) (http.Handler, error) {
 		return nil, errors.New("creation of inbound handler failed")
 	}
 
-	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+	return cors.Default().Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
```
Comment (troyronda) [inline pkg/didcomm/transport/http/inbound.go]: maybe split this into a couple lines :).

**Review by troyronda — APPROVED** [review]

File: pkg/didcomm/transport/http/inbound.go (hunk 1 above)
Comment (rolsonquadras) [reply pkg/didcomm/transport/http/inbound.go]: [Done](https://github.com/hyperledger/aries-framework-go/compare/701dca0d75e2995e951d53faa06cef20c2c16ff7..b394e22f2fdb5682cd144096a72968273a6843ef#diff-18bf71ef9d572ae715312cab65be25eeR38-R42)
