### PR TITLE
test: Update leveldb path for test run

### LINKED ISSUE #171: Extensibility of Verifiable Credential data model
Verifiable Credentials Data Model 1.0 supports extensions through the definition of links to custom JSON-LD based definitions.
https://w3c.github.io/vc-data-model/#extensibility

We need to provide a way to apply for valid schema extensions and read custom fields of Verifiable Credential into a dictionary or any other appropriate data structure.

### LINKED ISSUE #191: Build failure on `make unit-test`
[Log](https://circleci.com/gh/hyperledger/aries-framework-go/893)

Error:

```
[aries-framework/agentd] 2019/08/29 18:25:50 UTC - aries-agentd.main -> CRITICAL Failed to start aries agentd on port [localhost:8080], failed to initialize framework :  default option initialization failed: resolver initialization failed : resolver initialization failed : leveldb provider initialization failed : resource temporarily unavailable
FAIL	github.com/hyperledger/aries-framework-go/cmd/aries-agentd	0.011s
```

### PR DESCRIPTION
**Pull request by rolsonquadras**
Intermittently the test cases fail due to levelDB resource unavailability as parallel tests lock on file system.
Updated test cases to update path through global variable. This global variable will be removed once config are handled through struct (#148 and #175).

Closes #191 

Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

### CODE REVIEW

File: cmd/aries-agentd/main_test.go [hunk 1]
```diff
@@ -210,3 +216,16 @@ func TestStartAriesWithoutInboundHost(t *testing.T) {
 	}
 
 }
+
+func setupLevelDB(t testing.TB) (string, func()) {
```
Comment (llorllale) [inline cmd/aries-agentd/main_test.go]: This is only creating a temporary directory (with cleanup) - it is not setting up leveldb

**Comment by llorllale** [comment]
@rolsonquadras this PR closes #191 instead

File: pkg/restapi/restapi_test.go [hunk 2]
```diff
@@ -45,3 +52,16 @@ func TestNew_Success(t *testing.T) {
 	require.NotEmpty(t, controller.GetOperations())
 
 }
+
+func setupLevelDB(t testing.TB) (string, func()) {
```
Comment (llorllale) [inline pkg/restapi/restapi_test.go]: same here - it just creates temp path (returns cleanup)

File: cmd/aries-agentd/main_test.go (hunk 1 above)
Comment (rolsonquadras) [reply cmd/aries-agentd/main_test.go]: [Updated](https://github.com/hyperledger/aries-framework-go/compare/79f650938572126d2758278779bf911ef7c090a4..6f3a7d7e19a26a670b5002e34a70ea25c315587e#diff-7d0c01660ad47362e88877a74666c805R220).

File: pkg/restapi/restapi_test.go (hunk 2 above)
Comment (rolsonquadras) [reply pkg/restapi/restapi_test.go]: [Updated](https://github.com/hyperledger/aries-framework-go/compare/79f650938572126d2758278779bf911ef7c090a4..6f3a7d7e19a26a670b5002e34a70ea25c315587e#diff-aa5d1dd00855c1e6cbeffe4a26f9bc09R56) the name.

**Comment by rolsonquadras** [comment]
> @rolsonquadras this PR closes #191 instead

@llorllale my bad. updated the PR description.
