### PR TITLE
fix: #2146 add assertionMethod to did:peer

### LINKED ISSUE #2146: did:peer - missing a few verification method entries
The `did:peer` VDR is creating docs that can't be used for proofing VCs (`assertionMethod`) and is also missing [other relationships](https://www.w3.org/TR/did-core/#verification-relationships).

<detail><summary>Example</summary>

```json
{ 
    "@context": [
        "https://w3id.org/did/v1"
    ],
    "authentication": [
        "#CkPGqALPjt8PFWbYd4WmcNX4Qq3iXdUVq67s3yeh9vxe"
    ],      
    "created": "2020-08-10T16:13:22.45194098-04:00",
    "id": "did:peer:1zQmRtJYm9vMdFd4sedav1nyLjaMQp2BozhvTWkiWNSjbFq3",
    "publicKey": [
        {
            "controller": "#id",
            "id": "#CkPGqALPjt8PFWbYd4WmcNX4Qq3iXdUVq67s3yeh9vxe",
            "publicKeyBase58": "CkPGqALPjt8PFWbYd4WmcNX4Qq3iXdUVq67s3yeh9vxe",
            "type": "Ed25519VerificationKey2018"
        }
    ],
    "service": [
        {
            "id": "#agent",
            "priority": 0,
            "recipientKeys": [
                "CkPGqALPjt8PFWbYd4WmcNX4Qq3iXdUVq67s3yeh9vxe"
            ],
            "routingKeys": null,
            "serviceEndpoint": "http://example.com/didcomm",
            "type": "did-communication"
        }
    ],
    "updated": "2020-08-10T16:13:22.45194098-04:00"
} 
```

</details>

### PR DESCRIPTION
**Pull request by llorllale**
fixes #2146

<details><summary>Sample doc (new)</summary>

```json
{
  "@context": [
    "https://w3id.org/did/v1"
  ],  
  "id": "did:peer:1zQmPqCJKcwWZor8D4guhKm4WS7jzBRzcnR6tUpoSzMVFnQx",
  "publicKey": [
    {   
      "controller": "#id",
      "id": "#mxxxj4jvTOyLa-iSxUB-zqX36tTEan-RWwek3ovcDU4",
      "publicKeyBase58": "47T9HdrAD6NVuytFt5thuNC66RusZw4zjYs4Z4kBdxBs",
      "type": "Ed25519VerificationKey2018"
    }   
  ],  
  "service": [
    {   
      "id": "#agent",
      "priority": 0,
      "recipientKeys": [
        "47T9HdrAD6NVuytFt5thuNC66RusZw4zjYs4Z4kBdxBs"
      ],  
      "routingKeys": null,
      "serviceEndpoint": "didcomm:transport/queue",
      "type": "did-communication"
    }   
  ],  
  "authentication": [
    "#mxxxj4jvTOyLa-iSxUB-zqX36tTEan-RWwek3ovcDU4"
  ],  
  "assertionMethod": [
    "#mxxxj4jvTOyLa-iSxUB-zqX36tTEan-RWwek3ovcDU4"
  ],  
  "created": "2020-09-01T16:11:00.197961652-04:00",
  "updated": "2020-09-01T16:11:00.197961652-04:00"
}
```

</details>

Signed-off-by: George Aristy <george.aristy@securekey.com>

### CODE REVIEW

File: pkg/vdri/peer/did.go [hunk 1]
```diff
@@ -55,9 +61,10 @@ func NewDoc(publicKey []did.PublicKey, authentication []did.VerificationMethod,
 	return doc, nil
 }
 
-// computeDid creates the peer DID.
+// computeDidMethod1 creates the peer DID.
```
Comment (troyronda) [inline pkg/vdri/peer/did.go:64]: what does the 1 suffix signify?

Comment (llorllale) [reply pkg/vdri/peer/did.go:64]: The numeric algorithm used to compute the method-specific id:

> In this version of the spec, the multicodec descriptor for numalgo == 0 is dependent on key type and exactly matches the descriptor that would be used for the same value in did:key. The multicodec descriptor for numalgo == 1

[Source](https://identity.foundation/peer-did-method-spec/#method-specific-identifier)
