### PR TITLE
fix: credential manifest omit optional properties

### LINKED ISSUE #3335: Optional credential manifest fields are not omitted
There are several properties of credential manifests, credential fulfillments, and credential applications which are optional as per DIF specs. These properties were defined in the structs with the `omitempty` tag but were not actually omitted because there are no default empty values for embedded structs. This affected some validate functions as the assumption that certain fields do not exist were incorrect.

### PR DESCRIPTION
**Pull request by HeidiHan0000**
Closes #3335 

**Summary:**

- `omitempty` tag for mandatory properties were removed
- optional properties (with the `omitempty` tag) of custom types were changed to pointers so they can be omitted with the `omitempty` tag
- additional validation checks which were missing and more unit tests

### CODE REVIEW

File: pkg/doc/cm/credentialmanifest.go [hunk 1]
```diff
@@ -137,27 +136,68 @@ func (cm *CredentialManifest) UnmarshalJSON(data []byte) error {
...
+	err = ValidateOutputDescriptors(cm.OutputDescriptors)
 	if err != nil {
 		return err
 	}
 
 	return nil
 }
 
+func validateIssuer(issuer Issuer) error {
+	if issuer == (Issuer{}) {
```
Comment (DRK3) [inline pkg/doc/cm/credentialmanifest.go:161]: A better way to check this condition would be to make the `Issuer` field a pointer, rather than doing a struct value comparison like this. Strictly speaking, it doesn't make sense to say a non-pointer struct is "missing", since you don't know whether it was just defaulting to to the zero values or someone (for some reason) purposefully initialized it with zero values.

Alternatively, you might consider simply removing this check. Is there a meaningful difference between the entire `issuer` struct being missing and the issuer ID being missing?

**Review by DRK3 — CHANGES_REQUESTED** [review]

File: pkg/doc/cm/credentialmanifest.go (hunk 1 above)
Comment (HeidiHan0000) [reply pkg/doc/cm/credentialmanifest.go:161]: Oh that's true, I'll remove this check!

**Review by fqutishat — APPROVED** [review]
