### PR TITLE
fix: assign JWK from PublicKey of DID to resolved PublicKey

### LINKED ISSUE #1595: JsonWebSignature2020 verification fails
The JWK is not set in [verifiable.PublicKey](https://github.com/hyperledger/aries-framework-go/blob/7e4eafc4b66cf509b8010bb3fccf1265c1ccbf1f/pkg/doc/verifiable/common.go#L92) in common.go and this field is used in public key verifier to match the [verifiers](https://github.com/hyperledger/aries-framework-go/blob/7e4eafc4b66cf509b8010bb3fccf1265c1ccbf1f/pkg/doc/signature/verifier/public_key_verifier.go#L79).

### PR DESCRIPTION
**Pull request by kdimak**
closes #1595

Signed-off-by: Dmitriy Kinoshenko <dkinoshenko@gmail.com>

It should be also validated for the signature suites which use `JWK` from `verifier.PublicKey` in the VC BDD tests - https://github.com/hyperledger/aries-framework-go/issues/1596

### CODE REVIEW

File: pkg/doc/did/doc.go [hunk 1]
```diff
@@ -433,7 +433,7 @@ func decodePublicKeyJwk(jwkMap map[string]interface{}, publicKey *PublicKey) err
 	}
 
 	publicKey.Value = pkBytes
-	publicKey.jsonWebKey = &jwk
+	publicKey.JSONWebKey = &jwk
```
Comment (rolsonquadras) [inline pkg/doc/did/doc.go:436]: This will be set only when the rawDIDDoc has "publicKeyJwk". But when we create DIDDoc struct we set value and it internally converts to "publicKeyBase58" and we would be able to get back the "publicKeyJwk".

File: pkg/doc/did/doc.go [hunk 2]
```diff
@@ -115,7 +115,7 @@ type PublicKey struct {
 
 	Value []byte
 
-	jsonWebKey *jose.JWK
+	JSONWebKey *jose.JWK `json:"-"`
```
Comment (sudeshrshetty) [inline pkg/doc/did/doc.go:118]: why we need it? why can't we simply figure out key type by "Type" field and parse value to JWK?

**Comment by kdimak** [comment]
1. `jsonWebKey` field of the `did.PublicKey` is hidden, `JSONWebKey` getter is added.
2. Proper marshaling of `publicKeyJwk`, checked round-trip JSON conversion in `doc_test.go`.

File: pkg/doc/did/doc.go [hunk 3]
```diff
@@ -677,21 +698,33 @@ func populateRawPublicKey(context string, pk *PublicKey) map[string]interface{}
 		rawPK[jsonldController] = pk.Controller
 	}
 
-	if pk.Value != nil {
+	if pk.jsonWebKey != nil {
```
Comment (rolsonquadras) [inline pkg/doc/did/doc.go:701]: The jsonWebKey is not exposed. How can the user set this ?

Comment (kdimak) [reply pkg/doc/did/doc.go:701]: Should we give a user ability to set it? It's got defined when being unmarshalled from bytes.

Comment (rolsonquadras) [reply pkg/doc/did/doc.go:701]: How would this work with current version ? How does `pk.jsonWebKey` get set ?

Comment (kdimak) [reply pkg/doc/did/doc.go]: Reverted back to exposed `JSONWebKey`.

**Comment by kdimak** [comment]
> As discussed, are we gonna have a test to prove we don't lost any data while doing "bytes --> did.Doc --> bytes"?

We already had it at https://github.com/hyperledger/aries-framework-go/blob/397839f21ed4dd9e54e908a4a737702b42070d0b/pkg/doc/did/doc_test.go#L784, I added a test case to check conversion of `PublicKey` with `publicKeyJwk` defined.

**Comment by rolsonquadras** [comment]
> > As discussed, are we gonna have a test to prove we don't lost any data while doing "bytes --> did.Doc --> bytes"?
> 
> We already had it at
> 
> https://github.com/hyperledger/aries-framework-go/blob/397839f21ed4dd9e54e908a4a737702b42070d0b/pkg/doc/did/doc_test.go#L784
> 
> , I added a test case to check conversion of `PublicKey` with `publicKeyJwk` defined.

Do we have any test to show how to initialize JWK inside the DIDDoc struct and verify the case mentioned by @sudeshrshetty ?

File: pkg/doc/did/doc.go (hunk 2 above)
Comment (sudeshrshetty) [inline pkg/doc/did/doc.go:118]: As discussed expose it through function keep the variable private, to maintain standards among all format

Comment (kdimak) [reply pkg/doc/did/doc.go:118]: I really don't understand it. Why should we hide it? What's the standard? It's defined in https://www.w3.org/TR/did-core/#public-keys, `publicKeyJwk` field. Why should we expose `Value` field and don't export `JSONWebKey` field? What's the rule here?

**Comment by kdimak** [comment]
> > > As discussed, are we gonna have a test to prove we don't lost any data while doing "bytes --> did.Doc --> bytes"?
> > 
> > 
> > We already had it at
> > https://github.com/hyperledger/aries-framework-go/blob/397839f21ed4dd9e54e908a4a737702b42070d0b/pkg/doc/did/doc_test.go#L784
> > 
> > , I added a test case to check conversion of `PublicKey` with `publicKeyJwk` defined.
> 
> Do we have any test to show how to initialize JWK inside the DIDDoc struct and verify the case mentioned by @sudeshrshetty ?

There is no direct example of filling `JSONWebKey` inside DIDDoc, I can add the one if it's missing in your opinion. The  "bytes --> did.Doc --> bytes" test case is present, see `TestJSONConversion()`.

File: pkg/doc/did/doc.go (hunk 2 above)
Comment (rolsonquadras) [reply pkg/doc/did/doc.go:118]: + @troyronda @fqutishat

**Comment by rolsonquadras** [comment]
> > > > As discussed, are we gonna have a test to prove we don't lost any data while doing "bytes --> did.Doc --> bytes"?
> > > 
> > > 
> > > We already had it at
> > > https://github.com/hyperledger/aries-framework-go/blob/397839f21ed4dd9e54e908a4a737702b42070d0b/pkg/doc/did/doc_test.go#L784
> > > 
> > > , I added a test case to check conversion of `PublicKey` with `publicKeyJwk` defined.
> > 
> > 
> > Do we have any test to show how to initialize JWK inside the DIDDoc struct and verify the case mentioned by @sudeshrshetty ?
> 
> There is no direct example of filling `JSONWebKey` inside DIDDoc, I can add the one if it's missing in your opinion. The "bytes --> did.Doc --> bytes" test case is present, see `TestJSONConversion()`.

yes, I was asking about JSONWebKey.

**Comment by troyronda** [comment]
@kdimak we should add a JWK example.

File: pkg/doc/did/doc.go (hunk 1 above)
Comment (troyronda) [reply pkg/doc/did/doc.go:436]: btw - why aren't we using publicKeyJWK format internally instead of base58?

File: pkg/doc/did/doc_test.go [hunk 4]
```diff
@@ -804,6 +806,47 @@ func TestJSONConversion(t *testing.T) {
 	}
 }
 
+func TestJSONWebKey(t *testing.T) {
```
Comment (kdimak) [inline pkg/doc/did/doc_test.go:809]: Here is an example with DID Doc & JSON Web Key creation. @sudeshrshetty @rolsonquadras @troyronda

File: pkg/doc/did/doc.go (hunk 2 above)
Comment (sudeshrshetty) [reply pkg/doc/did/doc.go:118]: Some one who iterates through public key will be confused to use which one to use.

Comment (troyronda) [reply pkg/doc/did/doc.go:118]: I agree it's confusing to have both JSONWebKey and value/type exposed - these fields have similar purpose.

Comment (kdimak) [reply pkg/doc/did/doc.go]: Added `NewPublicKeyFromBytes()` and `NewPublicKeyFromJWK()` constructor functions. `jsonWebKey` field of `PublicKey` is hidden, added `JSONWebKey()` getter.

File: pkg/doc/did/doc.go [hunk 5]
```diff
@@ -118,6 +120,31 @@ type PublicKey struct {
...
+
+// NewPublicKeyFromJWK creates a new PublicKey based on JSON Web Key.
+func NewPublicKeyFromJWK(id, kType, controller string, jwk *jose.JWK) *PublicKey {
+	return &PublicKey{
+		ID:         id,
+		Type:       kType,
+		Controller: controller,
+		jsonWebKey: jwk,
+	}
+}
```
Comment (soluchok) [inline pkg/doc/did/doc.go:141]: nit: These functions do nothing. I would suggest to make `jsonWebKey` field public and remove these functions.

Comment (kdimak) [reply pkg/doc/did/doc.go:141]: Oh man, this is how it looked before, but this can confuse, please see starting comment https://github.com/hyperledger/aries-framework-go/pull/1597#discussion_r407567036 and scroll down :)

File: pkg/doc/did/doc.go [hunk 6]
```diff
@@ -118,6 +120,31 @@ type PublicKey struct {
...
+
+// NewPublicKeyFromJWK creates a new PublicKey based on JSON Web Key.
+func NewPublicKeyFromJWK(id, kType, controller string, jwk *jose.JWK) *PublicKey {
+	return &PublicKey{
+		ID:         id,
+		Type:       kType,
+		Controller: controller,
+		jsonWebKey: jwk,
```
Comment (troyronda) [inline pkg/doc/did/doc.go:139]: Do we not expose a value based on the JWK?
@kdimak @rolsonquadras @sudeshrshetty

File: pkg/doc/did/doc.go (hunk 5 above)
Comment (troyronda) [reply pkg/doc/did/doc.go:141]: I think that the specific problem is that we Value/Type has overlap with JWK contents. But I am confused about https://github.com/hyperledger/aries-framework-go/pull/1597#r408393621

File: pkg/doc/did/doc.go (hunk 6 above)
Comment (rolsonquadras) [reply pkg/doc/did/doc.go:139]: It's exposed through a public key method - https://github.com/hyperledger/aries-framework-go/pull/1597/files#diff-ca45993820e1e4b4338acd4e485ae699R144

Comment (troyronda) [reply pkg/doc/did/doc.go:139]: But now there is an exposed Value field that is nil for this case?

Comment (kdimak) [reply pkg/doc/did/doc.go:139]: Yes.

Comment (rolsonquadras) [reply pkg/doc/did/doc.go:139]: From the code, it looks like Value is always set and jsonWebKey is available through publicKey method for some cases - https://github.com/hyperledger/aries-framework-go/blob/47364c99607be0ebeea2395d9e7e97be0f1ed94d/pkg/doc/did/doc.go#L430-L436

Comment (kdimak) [reply pkg/doc/did/doc.go:139]: But if `did.Doc` is created manually using `NewPublicKeyFromJWK()` then `Value` is `nil`. To be consistent, we can convert `JWK` to bytes and fill in the `Value`.

Comment (kdimak) [reply pkg/doc/did/doc.go:145]: Updated `NewPublicKeyFromJWK()`. So now `PublicKey.Value` is always not nil. @rolsonquadras @troyronda
