### PR TITLE
fix: Pass VC Test Suite where JWS is passed as input data

### LINKED ISSUE #947: Pass VC Test Suite
Failing tests:
- Bad cardinality: https://github.com/w3c/vc-test-suite/issues/96, https://github.com/w3c/vc-test-suite/issues/97. Try to find solution on the **aries** side.
- Unknown public key for VC: https://github.com/w3c/vc-test-suite/issues/101. Use the RS256 public key from [config.json.example](https://github.com/w3c/vc-test-suite/blob/gh-pages/config.json.example), prepare own JWS and create PR at VC Test Suite. Also, consider replacing JWS of `verifiableCredential` inside VP (e.g. [example-016-jwt-presentation.jsonld](https://github.com/w3c/vc-test-suite/blob/gh-pages/test/vc-data-model-1.0/input/example-016-jwt-presentation.jsonld)).

Fail CI checks on test suite failure.

### PR DESCRIPTION
**Pull request by kdimak**
closes #947

Signed-off-by: Dima <dkinoshenko@gmail.com>

A number of VC Test Suite failures:
- Before: **14**
- After: **2**

A PR is made to enhance VC Test suite input data: https://github.com/w3c/vc-test-suite/pull/102

### CODE REVIEW

File: scripts/run_vc_test_suite.sh [hunk 1]
```diff
@@ -31,7 +31,8 @@ export PATH=$PATH:`pwd`
 
 # get the suite
 rm -rf ${SUITE_DIR}
-git clone --depth=1 -q https://github.com/w3c/vc-test-suite suite
+# todo clone from https://github.com/w3c/vc-test-suite as soon as https://github.com/w3c/vc-test-suite/pull/102 is merged.
+git clone --depth=1 -q https://github.com/kdimak/vc-test-suite -b vc-jwt-with-known-json-web-key suite
```
Comment (troyronda) [inline scripts/run_vc_test_suite.sh]: We should see if there is another way.

File: pkg/doc/verifiable/test-suite/verifiable_suite_test.go [hunk 2]
```diff
@@ -186,6 +187,39 @@ func parseKeys(packedKeys string) (private, public interface{}) {
 	return privateKey, publicKey
 }
 
+func getJWTDecodePublicKey() interface{} {
```
Comment (troyronda) [inline pkg/doc/verifiable/test-suite/verifiable_suite_test.go]: I do not think we should be hard-coding the key in the code.

The key provided in the command-line arguments should be used.

File: scripts/run_vc_test_suite.sh (hunk 1 above)
Comment (troyronda) [reply scripts/run_vc_test_suite.sh]: For a quick sanity check, I tried running the [jose](https://github.com/latchset/jose) tool on `example-016-jwt.jwt`.

```
jose jws ver -i example-016-jwt.jwt -k config.jwk                                                                                                                                  
Signature validation failed!
```

`config.jwk` contains the RSA JWK from `config.json.example`

Comment (kdimak) [reply scripts/run_vc_test_suite.sh]: Maybe `jose` CLU is doing something wrong? Here is a Golang code to test:
```
package main

import (
	"crypto/rsa"
	"log"

	"github.com/square/go-jose/v3/jwt"

	"github.com/square/go-jose/v3"
)

func main() {
	jwkStr := `
{
      "kty": "RSA",
      "n": "0vx7agoebGcQSuuPiLJXZptN9nndrQmbXEps2aiAFbWhM78LhWx4cbbfAAtVT86zwu1RK7aPFFxuhDR1L6tSoc_BJECPebWKRXjBZCiFV4n3oknjhMstn64tZ_2W-5JsGY4Hc5n9yBXArwl93lqt7_RN5w6Cf0h4QyQ5v-65YGjQR0_FDW2QvzqY368QQMicAtaSqzs8KJZgnYb9c7d0zgdAZHzu6qMQvRL5hajrn1n91CbOpbISD08qNLyrdkt-bFTWhAI4vMQFh6WeZu0fM4lFd2NcRwr3XPksINHaQ-G_xBniIqbw0Ls1jF44-csFCur-kEgU8awapJzKnqDKgw",
      "e": "AQAB",
      "d": "X4cTteJY_gn4FYPsXB8rdXix5vwsg1FLN5E3EaG6RJoVH-HLLKD9M7dx5oo7GURknchnrRweUkC7hT5fJLM0WbFAKNLWY2vv7B6NqXSzUvxT0_YSfqijwp3RTzlBaCxWp4doFk5N2o8Gy_nHNKroADIkJ46pRUohsXywbReAdYaMwFs9tv8d_cPVY3i07a3t8MN6TNwm0dSawm9v47UiCl3Sk5ZiG7xojPLu4sbg1U2jx4IBTNBznbJSzFHK66jT8bgkuqsk0GjskDJk19Z4qwjwbsnn4j2WBii3RL-Us2lGVkY8fkFzme1z0HbIkfz0Y6mqnOYtqc0X4jfcKoAC8Q",
      "p": "83i-7IvMGXoMXCskv73TKr8637FiO7Z27zv8oj6pbWUQyLPQBQxtPVnwD20R-60eTDmD2ujnMt5PoqMrm8RfmNhVWDtjjMmCMjOpSXicFHj7XOuVIYQyqVWlWEh6dN36GVZYk93N8Bc9vY41xy8B9RzzOGVQzXvNEvn7O0nVbfs",
      "q": "3dfOR9cuYq-0S-mkFLzgItgMEfFzB2q3hWehMuG0oCuqnb3vobLyumqjVZQO1dIrdwgTnCdpYzBcOfW5r370AFXjiWft_NGEiovonizhKpo9VVS78TzFgxkIdrecRezsZ-1kYd_s1qDbxtkDEgfAITAG9LUnADun4vIcb6yelxk",
      "dp": "G4sPXkc6Ya9y8oJW9_ILj4xuppu0lzi_H7VTkS8xj5SdX3coE0oimYwxIi2emTAue0UOa5dpgFGyBJ4c8tQ2VF402XRugKDTP8akYhFo5tAA77Qe_NmtuYZc3C3m3I24G2GvR5sSDxUyAN2zq8Lfn9EUms6rY3Ob8YeiKkTiBj0",
      "dq": "s9lAH9fggBsoFR8Oac2R_E2gw282rT2kGOAhvIllETE1efrA6huUUvMfBcMpn8lqeW6vzznYY5SSQF7pMdC_agI3nG8Ibp1BUb0JUiraRNqUfLhcQb_d9GF4Dh7e74WbRsobRonujTYN1xCaP6TO61jvWrX-L18txXw494Q_cgk",
      "qi": "GyM_p6JrXySiz1toFgKbWV-JdI3jQ4ypu9rbMWx3rQJBfmt0FoYzgUIZEVFEcOqwemRN81zoDAaa-Bk0KWNGDjJHZDdDmFhW3AN7lI-puxk_mHZGJ11rxyR8O55XLSe3SPmRfKwZI6yU24ZxvQKFYItdldUKGzO6Ia6zTKhAVRU",
      "alg": "RS256",
      "kid": "did:example:0xab#verikey-1"
}
`

	// old JWS from example-016-jwt.jwt
	//jws := "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImRpZDpleGFtcGxlOmFiZmUxM2Y3MTIxMjA0MzFjMjc2ZTEyZWNhYiNrZXlzLTEifQ.eyJzdWIiOiJkaWQ6ZXhhbXBsZTplYmZlYjFmNzEyZWJjNmYxYzI3NmUxMmVjMjEiLCJqdGkiOiJodHRwOi8vZXhhbXBsZS5lZHUvY3JlZGVudGlhbHMvMzczMiIsImlzcyI6ImRpZDpleGFtcGxlOmFiZmUxM2Y3MTIxMjA0MzFjMjc2ZTEyZWNhYiIsIm5iZiI6MTU0MTQ5MzcyNCwiZXhwIjoxNTczMDI5NzIzLCJub25jZSI6IjY2MCE2MzQ1RlNlciIsInZjIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vdzMub3JnLzIwMTgvY3JlZGVudGlhbHMvdjEiLCJodHRwczovL2V4YW1wbGUuY29tL2V4YW1wbGVzL3YxIl0sInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJVbml2ZXJzaXR5RGVncmVlQ3JlZGVudGlhbCJdLCJjcmVkZW50aWFsU3ViamVjdCI6eyJkZWdyZWUiOnsidHlwZSI6IkJhY2hlbG9yRGVncmVlIiwibmFtZSI6IkJhY2hlbG9yIG9mIFNjaWVuY2UgaW4gTWVjaGFuaWNhbCBFbmdpbmVlcmluZyJ9fX19.kaeFJM08sN7MthR-SWU-E8qbFoyZu2b_h1VllkEgNkLAGT9KpQbaeMUEti7QesFW_Cvwh5VErK62jneaW-uzZS6GPW3HVk8O3uRxWD3qCJx0l5uWZeHpRBX6yMcr2XGKWyFn0OBjoiGHQ78mHU8tNEWDqbrIhCoGQKj87OETvlfUDIkNi4_pRfLrJGh5HBrh6JuA-8uM2_clWC2RELsT52sPnqvMjm7UeYZgQEyaQJL6c41BUwHaCGWjUDCDZNWOd5M04s_Pi4Rqo97-2nbQRh_fuQk7aHKxb-UItQ8Mnk_hUFWEicwtuCfDFqwkZyW_r9dOBwz7-cOheuyP6OiLvw"

	// new JWS from example-016-jwt.jwt
	jws := "eyJhbGciOiJSUzI1NiIsImtpZCI6ImRpZDpleGFtcGxlOjB4YWIjdmVyaWtleS0xIiwidHlwIjoiSldUIn0.eyJleHAiOjE1NzMwMjk3MjMsImlhdCI6MTU0MTQ5MzcyNCwiaXNzIjoiZGlkOmV4YW1wbGU6YWJmZTEzZjcxMjEyMDQzMWMyNzZlMTJlY2FiIiwianRpIjoiaHR0cDovL2V4YW1wbGUuZWR1L2NyZWRlbnRpYWxzLzM3MzIiLCJuYmYiOjE1NDE0OTM3MjQsInN1YiI6ImRpZDpleGFtcGxlOmViZmViMWY3MTJlYmM2ZjFjMjc2ZTEyZWMyMSIsInZjIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIiwiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvZXhhbXBsZXMvdjEiXSwiY3JlZGVudGlhbFNjaGVtYSI6W10sImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImFsdW1uaU9mIjoiRXhhbXBsZSBVbml2ZXJzaXR5IiwiaWQiOiJkaWQ6ZXhhbXBsZTplYmZlYjFmNzEyZWJjNmYxYzI3NmUxMmVjMjEifSwiaXNzdWVyIjoiIiwidHlwZSI6WyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsIkFsdW1uaUNyZWRlbnRpYWwiXX19.IC4Bqm8HyRG5nZYgG02KiGQpxSxQpkWgZ0gcmZmQYWD3wZWJnLzc_hSFDEAzW59SMhqBTEkWPDLnCai21KqCyyW2N6qVmNUFWjifdGYdx4i5ute8LOSw2Qr20tnrsY03qwJtzrnSkg7vVVtj996iShA1EnCwDp13l_RoTDh3ZBRy3VX5uTF32h6rbSEMBsxpkJSl7ZglQnUJcwOjRlGwUGpavcgLASZ0uYu5pc2RX0woFgez23R0gZkrDGlgbTlgacaCDtoAz4kqTTLYOMOAWWJG5DRGtvYGjVJwJy5iOi2Uwg53hDUMS2crnj5IPa1ABQthkMviFlWKsyIY9NWLVA"

	jwk := &jose.JSONWebKey{}

	err := jwk.UnmarshalJSON([]byte(jwkStr))
	if err != nil {
		log.Panicf("JWK unmarshalling error: %v", err)
	}

	privateKey, ok := jwk.Key.(*rsa.PrivateKey)
	if !ok {
		log.Panicf("expected to get *rsa.PrivateKey, but got smth different")
	}

	parsedJwt, err := jwt.ParseSigned(jws)
	if err != nil {
		log.Panicf("parse VC from signed JWS: %v", err)
	}

	jwtClaims := new(jwt.Claims)

	err = parsedJwt.UnsafeClaimsWithoutVerification(jwtClaims)
	if err != nil {
		log.Panicf("parse VC JWT claims: %v", err)
	}

	if err = parsedJwt.Claims(privateKey.Public(), jwtClaims); err != nil {
		log.Panicf("verify JWT signature: %v", err)
	}

	log.Println("Good one!")
}

```

File: pkg/doc/verifiable/test-suite/verifiable_suite_test.go (hunk 2 above)
Comment (kdimak) [reply pkg/doc/verifiable/test-suite/verifiable_suite_test.go]: The thing is that  JWS from VC Test Suite are static - they are not re-build based on the keys provided to the Suite in `config.json`. We can actually customize the keys and they then will differ from the original key used to prepare static JWS in the Suite. That's why I want to emphasize that the key is hardcoded and does not depend on `config.json`.

I am thinking that we may probably propose to generate `example-016-jwt.jwt` (i.e. not to use hard-coded value) in the Suite to avoid such uncertainty.

Comment (kdimak) [reply pkg/doc/verifiable/test-suite/verifiable_suite_test.go]: After discussion with @troyronda , this is made simpler - use the RSA key from `config.json` to verify the signature.

File: scripts/run_vc_test_suite.sh (hunk 1 above)
Comment (troyronda) [reply scripts/run_vc_test_suite.sh]: I meant a sanity check on the original file in the test suite, to ensure it didn't verify with an external tool either :).

File: scripts/run_vc_test_suite.sh [hunk 3]
```diff
@@ -31,7 +31,8 @@ export PATH=$PATH:`pwd`
 
 # get the suite
 rm -rf ${SUITE_DIR}
-git clone --depth=1 -q https://github.com/w3c/vc-test-suite suite
+# todo clone from https://github.com/w3c/vc-test-suite as soon as https://github.com/w3c/vc-test-suite/pull/102 is merged.
```
Comment (troyronda) [inline scripts/run_vc_test_suite.sh]: It would be nice to simply patch example 16 signatures rather than using a fork of the entire repo.

**Comment by llorllale** [comment]
> We will need to revisit the patched test cases.

Indeed. I saw unanswered questions in the VC testsuite repo (eg. "what key was used to sign in this test?")
