### PR TITLE
fix: make run-openapi-demo fails

### LINKED ISSUE #918: Issue starting OpenAPI demo
**What I'm trying to do**

I'm trying to run the OpenAPI demo using
`make run-openapi-demo`

**Actual result**

```
Starting demo agent rest containers ...
docker-compose -f docker-compose-demo.yml -f /aries-framework-go/test/bdd/fixtures/agent-rest/docker-compose.yml -f /aries-framework-go/test/bdd/fixtures/sidetree-mock/docker-compose.yml up --force-recreate
ERROR: Network agent-rest_bdd_net declared as external, but could not be found. Please create the network manually using `docker network create agent-rest_bdd_net` and try again.
```

I tried the suggestion 
`docker network create agent-rest_bdd_net`
but the same error appears on running the demo again.

### PR DESCRIPTION
**Pull request by sandrask**
Closes #918

Signed-off-by: Sandra Vrtikapa <sandra.vrtikapa@securekey.com>

### CODE REVIEW

File: scripts/run-openapi-demo.sh [hunk 1]
```diff
@@ -26,7 +26,9 @@ set -o allexport
...
 
+cd $AGENT_COMPOSE_FILE
+docker-compose -f docker-compose.yml  ${DEMO_COMPOSE_OP} -d
+cd $SIDETREE_COMPOSE_FILE
+docker-compose -f docker-compose.yml ${DEMO_COMPOSE_OP} -d
 cd $DEMO_PATH
-echo docker-compose -f docker-compose-demo.yml -f ${AGENT_COMPOSE_FILE} -f ${SIDETREE_COMPOSE_FILE} ${DEMO_COMPOSE_OP}
-docker-compose -f docker-compose-demo.yml -f ${AGENT_COMPOSE_FILE} -f ${SIDETREE_COMPOSE_FILE} ${DEMO_COMPOSE_OP}
-
+docker-compose -f docker-compose.yml ${DEMO_COMPOSE_OP} -d
```
Comment (troyronda) [inline scripts/run-openapi-demo.sh]: when do these fixtures get stopped?

Comment (sandrask) [reply scripts/run-openapi-demo.sh]: we have make clean and make clean-fixtures targets that will stop containers

Comment (troyronda) [reply scripts/run-openapi-demo.sh]: Why do we need to start with `-d` anyways?

We haven't previously done this.
