### PR TITLE
fix: set key for KeyAgreement as embedded

### LINKED ISSUE #1849: did:key doesn't specify that key for KeyAgreement is embedded
This causes the wrong handling of the KeyAgreement section by JSONBytes() method.

Fix also misleading error message in: https://github.com/hyperledger/aries-framework-go/blob/dcc599e23d096d26a3332dc047fe75bfe9cdaf62/pkg/doc/did/doc.go#L310

### PR DESCRIPTION
**Pull request by aholovko**
Fixes #1849

Signed-off-by: Andriy Holovko <andriy.holovko@gmail.com>

### CODE REVIEW

File: pkg/vdri/key/creator.go [hunk 1]
```diff
@@ -61,7 +61,7 @@ func createDoc(pubKeyValue []byte) (*did.Doc, error) {
 		AssertionMethod:      []did.VerificationMethod{{PublicKey: *pubKey}},
 		CapabilityDelegation: []did.VerificationMethod{{PublicKey: *pubKey}},
 		CapabilityInvocation: []did.VerificationMethod{{PublicKey: *pubKey}},
-		KeyAgreement:         []did.VerificationMethod{{PublicKey: *keyAgreement}},
+		KeyAgreement:         []did.VerificationMethod{{PublicKey: *keyAgreement, Embedded: true}},
```
Comment (kdimak) [inline pkg/vdri/key/creator.go:64]: I think we should also fill `Relationship` field here for consistency.
For the better user experience, I would add the following factory methods of the `VerificationMethod`:
```
func NewEmbeddedVerificationMethod(pk PublicKey, r VerificationRelationship) *VerificationMethod {
	return &VerificationMethod{
		PublicKey:    pk,
		Relationship: r,
		Embedded:     true,
	}
}

func NewReferencedVerificationMethod(pk PublicKey, r VerificationRelationship, isRelativeURL bool) *VerificationMethod {
	return &VerificationMethod{
		PublicKey:    pk,
		Relationship: r,
		RelativeURL:  isRelativeURL,
	}
}
```

and will use it here:
```
	return &did.Doc{
		Context:              []string{schemaV1},
		ID:                   didKey,
		PublicKey:            []did.PublicKey{*pubKey},
		Authentication:       []did.VerificationMethod{
			*did.NewReferencedVerificationMethod(*pubKey, did.Authentication, false)},
		AssertionMethod:      []did.VerificationMethod{
			*did.NewReferencedVerificationMethod(*pubKey, did.AssertionMethod, false)},
		CapabilityDelegation: []did.VerificationMethod{
			*did.NewReferencedVerificationMethod(*pubKey, did.CapabilityDelegation, false)},
		CapabilityInvocation: []did.VerificationMethod{
			*did.NewReferencedVerificationMethod(*pubKey, did.CapabilityInvocation, false)},
		KeyAgreement:         []did.VerificationMethod{
			*did.NewEmbeddedVerificationMethod(*keyAgreement, did.KeyAgreement)},
		Created:              &t,
		Updated:              &t,
	}, nil
```
