### PR TITLE
fix: stutter in aries-js-worker API for browser mode

### LINKED ISSUE #1293: bug: Aries JS Woker API export stutter

### PR DESCRIPTION
**Pull request by sudeshrshetty**
- closes #1293

Signed-off-by: sudesh.shetty <sudesh.shetty@securekey.com>

### CODE REVIEW

**Comment by llorllale** [comment]
@sudeshrshetty what does this look like on node.js?

File: cmd/aries-js-worker/src/aries.js [hunk 1]
```diff
@@ -78,7 +78,19 @@ function newMsg(pkg, fn, payload) {
...
-// TODO implement Aries options
+/**
+ * Aries framework class provides Aries SSI-agent features.
+ * @param opts are framework initialization options.
+ * @class
+ */
+export const Framework = class {
+    constructor(opts) {
+        return (async () => {
+            return await Aries(opts);
```
Comment (llorllale) [inline cmd/aries-js-worker/src/aries.js]: `Aries()` isn't an async function

Comment (llorllale) [reply cmd/aries-js-worker/src/aries.js]: I'm realizing now that `Aries()` should've been un-exported.

Comment (llorllale) [reply cmd/aries-js-worker/src/aries.js]: Fixed in PR #1291
