### PR TITLE
docs: Fixes openapi validation warnings

### LINKED ISSUE #1975: fix openapi validation warning
```
Validating generated spec
2020/07/02 14:21:33
The swagger spec at "/home/llorllale/dev/hyperledger/aries-framework-go/build/rest/openapi/spec/openAPI.yml" is valid against swagger specification 2.0
2020/07/02 14:21:33
The swagger spec at "/home/llorllale/dev/hyperledger/aries-framework-go/build/rest/openapi/spec/openAPI.yml" showed up some valid but possibly unwanted constructs.
2020/07/02 14:21:33 See warnings below:
2020/07/02 14:21:33 - WARNING: definition "#/definitions/eventProps" is not used anywhere
```

### PR DESCRIPTION
**Pull request by soluchok**
This PR fixes collisions related to Invitation and Action structures. 

What was the problem?
We have two `Invitation` structures in our framework (outofband and didexchange).
When we generate `swagger` it uses only one `Invitation` definition e.g '#/definitions/Invitation'.
Due to this collision the spec was incorrect.
The same was related to the `Action` structure.

Closes #1975 

Signed-off-by: Andrii Soluk <isoluchok@gmail.com>

### CODE REVIEW

File: pkg/didcomm/protocol/outofband/service_test.go [hunk 1]
```diff
@@ -148,11 +148,7 @@ func TestHandleInbound(t *testing.T) {
 		case e := <-events:
 			require.Equal(t, Name, e.ProtocolName)
 			require.Equal(t, expected, e.Message)
-			require.NotNil(t, e.Properties)
-			props, ok := e.Properties.(*eventProps)
-			require.True(t, ok)
-			require.Empty(t, props.ConnectionID())
-			require.NoError(t, props.Error())
+			require.Nil(t, e.Properties)
```
Comment (llorllale) [inline pkg/didcomm/protocol/outofband/service_test.go:151]: why did this change?

Comment (soluchok) [reply pkg/didcomm/protocol/outofband/service_test.go:151]: I removed properties from the Action event. They were unused.
