### PR TITLE
fix: #1997 didexchange.Client.SaveConnection not saving 'theirDID'

### LINKED ISSUE #1997: didexchange.Client.SaveConnection not saving 'theirDID'
PR #1990 extended `didexchange.Client.SaveConnection()` such that it saved the did mappings to the did store, but that is not enough: `theirDID` did document needs to be saved as well in order for the outbound dispatcher to resolve the correct didcomm destinations (src recipientKey, destination recipientKeys, endpoint, routingKeys).

### PR DESCRIPTION
**Pull request by llorllale**
fixes #1997 

* refactored SaveConnection() -> CreateConnection()
* Parameters are now: myDID string, theirDID *did.Doc, and options
* REST/Controller APIs refactored accordingly
* fix: did:peer vdri not returning vdriapi.ErrNotFound when deltas not
  found

BDD tests TODO #1997 (but I've tested this change in another project's bdd tests)

Signed-off-by: George Aristy <george.aristy@securekey.com>

### CODE REVIEW

File: pkg/client/didexchange/client_test.go [hunk 1]
```diff
@@ -1247,3 +1248,34 @@ func generateKeyPair() (string, []byte) {
...
+	require.NoError(t, err)
+
+	key := did.PublicKey{
+		ID:         uuid.New().String(),
+		Type:       "Ed25519VerificationKey2018",
+		Controller: "did:example:123",
+		Value:      pubKey,
+	}
+	doc, err := peer.NewDoc(
+		[]did.PublicKey{key},
```
Comment (Baha-sk) [inline pkg/client/didexchange/client_test.go:1263]: is `did.PublicKey` supposed to be the same as `did.VerificationMethod.PublicKey` as well as did.Service.RecipientKeys.

We need to start distinguishing encryption keys from verification keys. This is particularly important with the new Authcrypt/Anoncrypt packers which use valid KMS generated encryption keys. I'm interested to know how to integrate these keys along with DID verification keys to update didComm with the new Packers.

File: pkg/controller/rest/didexchange/operation_test.go [hunk 2]
```diff
@@ -534,3 +549,41 @@ func verifyRESTError(t *testing.T, code command.Code, data []byte) {
...
+			RecipientKeys:   []string{base58.Encode(pubKey)},
+			ServiceEndpoint: "http://example.com",
+		}}),
+	)
+	require.NoError(t, err)
+
+	return doc
+}
+
+func marshalDoc(t *testing.T, d *did.Doc) []byte {
```
Comment (soluchok) [inline pkg/controller/rest/didexchange/operation_test.go:584]: better to add `t.Helper()` here

File: pkg/controller/command/didexchange/command_test.go [hunk 3]
```diff
@@ -16,11 +16,13 @@ import (
 	"testing"
 	"time"
 
+	"github.com/hyperledger/aries-framework-go/pkg/doc/did"
+	"github.com/hyperledger/aries-framework-go/pkg/vdri/peer"
+
```
Comment (soluchok) [inline pkg/controller/command/didexchange/command_test.go:21]: wrong import

File: pkg/controller/command/didexchange/command_test.go [hunk 4]
```diff
@@ -942,3 +950,41 @@ func generateKeyPair() (string, []byte) {
...
+			RecipientKeys:   []string{base58.Encode(pubKey)},
+			ServiceEndpoint: "http://example.com",
+		}}),
+	)
+	require.NoError(t, err)
+
+	return doc
+}
+
+func toBytes(t *testing.T, v interface{}) []byte {
```
Comment (soluchok) [inline pkg/controller/command/didexchange/command_test.go:985]: also need to add `t.Helper()`

File: pkg/controller/command/didexchange/command_test.go [hunk 5]
```diff
@@ -942,3 +950,41 @@ func generateKeyPair() (string, []byte) {
...
+			Embedded:     true,
+			RelativeURL:  false,
+		}},
+		did.WithService([]did.Service{{
+			ID:              "didcomm",
+			Type:            "did-communication",
+			Priority:        0,
+			RecipientKeys:   []string{base58.Encode(pubKey)},
+			ServiceEndpoint: "http://example.com",
+		}}),
```
Comment (soluchok) [inline pkg/controller/command/didexchange/command_test.go:978]: default values can be removed e.g `Relationship, RelativeURL and Priority `

File: pkg/controller/rest/didexchange/models.go [hunk 6]
```diff
@@ -201,14 +201,27 @@ type RemoveConnectionRequest struct { // nolint: unused,deadcode
...
+//
+// Request to create a new connection between two DIDs.
+//
+// swagger:parameters createConnection
+type createConnectionRequest struct { // nolint: unused,deadcode
+	// Params for creating a connection.
+	//
+	// in: body
+	// required: true
+	Request didexchange.CreateConnectionRequest
```
Comment (soluchok) [inline pkg/controller/rest/didexchange/models.go:226]: Should be:
```
/// in: body
Body struct {
	// required: true
	Request didexchange.CreateConnectionRequest
}
```

Comment (llorllale) [reply pkg/controller/rest/didexchange/models.go:226]: @soluchok can you give an example of the swagger output you're looking for?

This is the current output:

```yaml
  /connections/create:
    post:
      operationId: createConnection
      parameters:
      - description: Params for creating a connection.
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/CreateConnectionRequest'
      responses:
        "200":
          $ref: '#/responses/createConnectionResp'
        default:
          $ref: '#/responses/genericError'
      summary: Saves the connection record.
      tags:
      - did-exchange
```

```yaml
  CreateConnectionRequest:
    description: CreateConnectionRequest model
    properties:
      implicit:
        type: boolean
        x-go-name: Implicit
      invitationDID:
        type: string
        x-go-name: InvitationDID
      invitationID:
        type: string
        x-go-name: InvitationID
      myDID:
        type: string
        x-go-name: MyDID
      parentThreadID:
        type: string
        x-go-name: ParentThreadID
      theirDID:
        $ref: '#/definitions/DIDDocument'
      theirLabel:
        type: string
        x-go-name: TheirLabel
      threadID:
        type: string
        x-go-name: ThreadID
    type: object
    x-go-package: github.com/hyperledger/aries-framework-go/pkg/controller/command/didexchange

```

File: pkg/client/didexchange/client_test.go (hunk 1 above)
Comment (llorllale) [reply pkg/client/didexchange/client_test.go:1263]: @Baha-sk 

> is did.PublicKey supposed to be the same as did.VerificationMethod.PublicKey as well as did.Service.RecipientKeys.

No, but sadly there are a ton of assumptions already baked into the framework. Unpacking (pun) all of this will take effort.

> We need to start distinguishing encryption keys from verification keys. This is particularly important with the new Authcrypt/Anoncrypt packers which use valid KMS generated encryption keys. I'm interested to know how to integrate these keys along with DID verification keys to update didComm with the new Packers.

Yes. I'm happy to chat about it.

DIDComm - as it currently stands in Aries - is an odd case. It inlines the keys into the `did-communication` service entry. The location of these inlined keys may (probably will) change as the DIF/didcomm-messaging work evolves.

File: pkg/controller/rest/didexchange/models.go (hunk 6 above)
Comment (llorllale) [reply pkg/controller/rest/didexchange/models.go:226]: Note this other example from the same file:

https://github.com/hyperledger/aries-framework-go/blob/27f435692fd574ab373e76f340d383b80c9a2a9e/pkg/controller/rest/didexchange/models.go#L31-L39

File: pkg/controller/command/didexchange/command_test.go (hunk 5 above)
Comment (llorllale) [reply pkg/controller/command/didexchange/command_test.go]: @soluchok done

File: pkg/controller/command/didexchange/command_test.go (hunk 4 above)
Comment (llorllale) [reply pkg/controller/command/didexchange/command_test.go:981]: @soluchok done

File: pkg/controller/command/didexchange/command_test.go (hunk 3 above)
Comment (llorllale) [reply pkg/controller/command/didexchange/command_test.go]: @soluchok done

File: pkg/controller/rest/didexchange/operation_test.go (hunk 2 above)
Comment (llorllale) [reply pkg/controller/rest/didexchange/operation_test.go:586]: @soluchok done

File: pkg/client/didexchange/client.go [hunk 7]
```diff
@@ -284,31 +285,33 @@ func (c *Client) GetConnectionAtState(connectionID, stateID string) (*Connection
...
-		ServiceEndPoint: req.ServiceEndPoint,
-		RecipientKeys:   req.RecipientKeys,
-		RoutingKeys:     req.RoutingKeys,
-		InvitationID:    req.InvitationID,
-		Namespace:       connection.MyNSPrefix,
-	}
-
-	err := c.didexchangeSvc.SaveConnectionRecord(rec)
+// CreateConnection creates a new connection between myDID and theirDID and returns the connectionID.
+func (c *Client) CreateConnection(myDID string, theirDID *did.Doc, options ...ConnectionOption) (string, error) {
```
Comment (rolsonquadras) [inline pkg/client/didexchange/client.go:289]: Probably theriDIDDoc would be more helpful to differentiate between DID and DIDDoc as currently we have `myDID`(which is a string) ad `theirDID`(which is of type *did.Doc).

File: pkg/controller/command/didexchange/command.go [hunk 8]
```diff
@@ -160,7 +161,7 @@ func (c *Command) GetHandlers() []command.Handler {
 		cmdutil.NewCommandHandler(commandName, createInvitationCommandMethod, c.CreateInvitation),
 		cmdutil.NewCommandHandler(commandName, receiveInvitationCommandMethod, c.ReceiveInvitation),
 		cmdutil.NewCommandHandler(commandName, acceptInvitationCommandMethod, c.AcceptInvitation),
-		cmdutil.NewCommandHandler(commandName, saveConnectionCommandMethod, c.SaveConnection),
+		cmdutil.NewCommandHandler(commandName, createConnectionCommandMethod, c.CreateConnection),
```
Comment (rolsonquadras) [inline pkg/controller/command/didexchange/command.go:164]: We would need to update the wasm call - https://github.com/hyperledger/aries-framework-go/blob/016c620b82faa4c601ef183b421dc624dc2e3848/cmd/aries-js-worker/src/aries.js#L680

File: pkg/controller/rest/didexchange/models.go (hunk 6 above)
Comment (soluchok) [reply pkg/controller/rest/didexchange/models.go:226]: Sorry, my fault. I thought we need a `Request` field as well.
eg. 
```
{
"myDID": "string"
...
}
vs
{
    "request":{
        "myDID": "string"
        ...
    }
}
```
But `createConnectionResp` is definitely wrong. Should be:
```
type createConnectionResp struct { // nolint: unused,deadcode
	// The ID of the connection to get
	//
	// in: body
	Body struct {
		ID string `json:"id"`
	}
}
```

Comment (soluchok) [reply pkg/controller/rest/didexchange/models.go:226]: > Note this other example from the same file:
> 
> https://github.com/hyperledger/aries-framework-go/blob/27f435692fd574ab373e76f340d383b80c9a2a9e/pkg/controller/rest/didexchange/models.go#L31-L40

it is wrong. it will show only the `didexchangeSvc.Invitation` structure. All tags will be ignored `alias , invitation, invitation_url `

Comment (llorllale) [reply pkg/controller/rest/didexchange/models.go:226]: @soluchok 



> > Note this other example from the same file:
> > https://github.com/hyperledger/aries-framework-go/blob/27f435692fd574ab373e76f340d383b80c9a2a9e/pkg/controller/rest/didexchange/models.go#L31-L40
> 
> it is wrong. it will show only the `didexchangeSvc.Invitation` structure. All tags will be ignored `alias , invitation, invitation_url `

Verified:

```yaml
  /connections/create-invitation:
    post:
      operationId: createInvitation
      parameters:
      - description: The Alias to be used in invitation to be created
        in: query
        name: alias
        type: string
        x-go-name: Alias
      - description: Optional public DID to be used in invitation
        in: query
        name: public
        type: string
        x-go-name: Public
      responses:
        "200":
          $ref: '#/responses/createInvitationResponse'
        default:
          $ref: '#/responses/genericError'
      summary: Creates a new connection invitation....
      tags:
      - did-exchange
```

```yaml
  createInvitationResponse:
    description: |-
      createInvitationResponse model

      This is used for returning a create invitation response with a single connection invitation as body
    schema:
      $ref: '#/definitions/Invitation'
```

Comment (llorllale) [reply pkg/controller/rest/didexchange/models.go:226]: @soluchok 

> But `createConnectionResp` is definitely wrong. Should be:
> 
> ```
> type createConnectionResp struct { // nolint: unused,deadcode
> 	// in: body
> 	Body struct {
> 	       // The ID of the connection to get
> 	       //
> 		ID string `json:"id"`
> 	}
> }
> ```

Fixed. New swagger output:

```yaml
  createConnectionResp:
    description: |-
      createConnectionResp model

      This is used as the response model for save connection api.
    schema:
      properties:
        id:
          description: The ID of the connection to get
          type: string
          x-go-name: ID
      type: object
```

File: pkg/controller/command/didexchange/command.go (hunk 8 above)
Comment (llorllale) [reply pkg/controller/command/didexchange/command.go:164]: @rolsonquadras fixed
