### PR TITLE
fix: Leave BBS+ Selective Disclosure proofs only

### LINKED ISSUE #2440: Leave BBS+ Selective Disclosure proofs only
When creating BBS+ selective disclosure, leave only BBS+ Signatures converted to BBS+ Signature proofs. Other signatures must be removed as their check would fail because of test data mismatch on verification.

### PR DESCRIPTION
**Pull request by kdimak**
When creating BBS+ selective disclosure, only BBS+ Signatures converted to BBS+ Signature proofs are left in the result document (e.g. VC). Other signatures are removed as otherwise, their check would fail because of test data mismatch on the verification stage.
Also, we now produce selective disclosure for all present BBS+ Signatures (before we did this for the very first one found in the `proof` list).

closes #2440

Signed-off-by: Dmitriy Kinoshenko <dkinoshenko@gmail.com>

### CODE REVIEW

File: pkg/doc/signature/suite/bbsblssignatureproof2020/suite_test.go [hunk 1]
```diff
@@ -132,9 +132,18 @@ func (v *testVerifier) Verify(_ *sigverifier.PublicKey, doc, _ []byte) error {
...
-func (r *testKeyResolver) Resolve(string) (*sigverifier.PublicKey, error) {
+func (r *testKeyResolver) Resolve(id string) (*sigverifier.PublicKey, error) {
+	if r.err != nil {
+		return nil, r.err
+	}
+
+	if len(r.variants) > 0 {
+		return r.variants[id], nil
+	}
+
```
Comment (soluchok) [inline pkg/doc/signature/suite/bbsblssignatureproof2020/suite_test.go:147]: It seems like a bug. How about 
```
if val,ok := r.variants[id];ok{
    return val,nil
}
```

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go [hunk 2]
```diff
@@ -104,40 +123,26 @@ func getPublicKeyAndSignature(blsProofMap map[string]interface{}, resolver keyRe
...
-	var blsProof map[string]interface{}
-
-	for i, proof := range allProofs {
-		if proof["type"] == "https://w3c-ccg.github.io/ldp-bbs2020/context/v1#BbsBlsSignature2020" {
-			blsProofInd = i
-			allProofs = deleteProof(allProofs, i)
-			blsProof = proof
-			blsProof["@context"] = securityContext
+	for _, p := range allProofs {
+		if p["type"] == "https://w3c-ccg.github.io/ldp-bbs2020/context/v1#BbsBlsSignature2020" {
```
Comment (soluchok) [inline pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go:135]: use a constant here

**Review by soluchok — APPROVED** [review]

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go [hunk 3]
```diff
@@ -45,29 +45,51 @@ func (s *Suite) SelectiveDisclosure(doc map[string]interface{}, revealDoc map[st
...
+		if dErr != nil {
+			return nil, dErr
+		}
+
+		if i == 0 {
+			revealDocumentResult = revealedDoc
+			revealDocumentResult["proof"] = make([]map[string]interface{}, len(blsSignatures))
+		}
+
+		proofs := revealDocumentResult["proof"].([]map[string]interface{}) //nolint:errcheck
```
Comment (Baha-sk) [inline pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go:67]: why `nolint:errcheck` here?

File: pkg/doc/signature/suite/bbsblssignatureproof2020/suite_test.go (hunk 1 above)
Comment (kdimak) [reply pkg/doc/signature/suite/bbsblssignatureproof2020/suite_test.go:147]: `r.variants` could be undefined. If defined, it should contain the target key (as this code is used for tests)

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go (hunk 3 above)
Comment (kdimak) [reply pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go:67]: This code is not clean. I will simplify this.

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go [hunk 4]
```diff
@@ -45,44 +46,65 @@ func (s *Suite) SelectiveDisclosure(doc map[string]interface{}, revealDoc map[st
...
-	blsProof := proofInfo.blsProof
+	var revealDocumentResult map[string]interface{}
+
+	proofs := make([]map[string]interface{}, len(blsSignatures))
+
+	for i, blsProof := range blsSignatures {
+		revealedDoc, derivedProof, dErr := generateSignatureProof(blsProof, resolver, docCompacted,
+			revealDoc, nonce, opts...)
+		if dErr != nil {
+			return nil, dErr
```
Comment (llorllale) [inline pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go:62]: Please wrap this error.

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go [hunk 5]
```diff
@@ -45,44 +46,65 @@ func (s *Suite) SelectiveDisclosure(doc map[string]interface{}, revealDoc map[st
...
+
+func generateSignatureProof(blsProof map[string]interface{}, resolver keyResolver, docCompacted map[string]interface{},
+	revealDoc map[string]interface{}, nonce []byte, opts ...jsonld.ProcessorOpts) (
+	map[string]interface{}, map[string]interface{}, error) {
+	bls := bbs12381g2pub.New()
 
 	pubKeyBytes, signatureBytes, err := getPublicKeyAndSignature(blsProof, resolver)
 	if err != nil {
-		return nil, err
+		return nil, nil, err
```
Comment (llorllale) [inline pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go:84]: Please wrap these errors.

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go [hunk 6]
```diff
@@ -45,44 +46,65 @@ func (s *Suite) SelectiveDisclosure(doc map[string]interface{}, revealDoc map[st
...
 	}
 
 	verData, err := buildVerificationData(docCompacted, blsProof, revealDoc, opts...)
 	if err != nil {
-		return nil, err
+		return nil, nil, err
```
Comment (llorllale) [inline pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go:89]: Please wrap this error.

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go [hunk 7]
```diff
@@ -45,44 +46,65 @@ func (s *Suite) SelectiveDisclosure(doc map[string]interface{}, revealDoc map[st
...
 		return nil, err
 	}
 
-	blsProof := proofInfo.blsProof
+	var revealDocumentResult map[string]interface{}
+
+	proofs := make([]map[string]interface{}, len(blsSignatures))
+
+	for i, blsProof := range blsSignatures {
+		revealedDoc, derivedProof, dErr := generateSignatureProof(blsProof, resolver, docCompacted,
```
Comment (llorllale) [inline pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go:59]: can the revealedDoc from the first iteration be reused for the rest?

Comment (llorllale) [reply pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go:59]: Reason I ask is because these JSON-LD operations seem expensive from my experience. Especially considering that there are probably network calls being made.

I suspect JSON-LD is one of the reasons why our zcapld implementation is slow.

Comment (kdimak) [reply pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go:59]: I got it. Great input, thank you! Let me change the program flow in this regard.

Comment (kdimak) [reply pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go]: Refactored.

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go (hunk 6 above)
Comment (kdimak) [reply pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go]: Done.

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go (hunk 5 above)
Comment (kdimak) [reply pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go]: Done.

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go (hunk 4 above)
Comment (kdimak) [reply pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go]: Done.

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go (hunk 3 above)
Comment (kdimak) [reply pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go]: Done.

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go (hunk 2 above)
Comment (kdimak) [reply pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go]: Done.

**Review by troyronda — APPROVED** [review]

**Review by Baha-sk — APPROVED** [review]
