### PR TITLE
fix: json-ld strict validation on mapped schema elements

### LINKED ISSUE #1781: json-ld strict validation on mapped schema elements
Validation of
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://schema.org/",
    "https://mavennet.github.io/contexts/bill-of-lading-v1.0.jsonld"
  ],
  "id": "http://neo-flow.com/credentials/e94a16cb-35b2-4301-9fb6-7af3d8fe7b81",
  "type": ["VerifiableCredential", "BillOfLadingCredential"],
  "name": "Bill of Lading",
  "description": "Detailed shipment document provided by the carrier to the receiver of products.",
  "issuer": "did:v1:test:nym:z6MkfG5HTrBXzsAP8AbayNpG3ZaoyM4PCqNPrdWQRSpHDV6J",
  "issuanceDate": "2020-04-09T21:13:13Z",
  "credentialSubject": {
    "productIdentifier": "3a185b8f-078a-4646-8343-76a45c2856a5",
    "bolNumber": "BOL000104976",
    "carrier": "did:v1:test:nym:z6MkhdmzFu659ZJ4XKj31vtEDmjvsi5yDZG5L7Caz63oP39k",
    "recipient": "did:v1:test:nym:z6MknQLHcwKwopce5ji1Ftsurn8mNL58wTxZB238uEMsegUj",
    "transportType": "Pipeline",
    "originAddress": {
      "address": "Quebec, CAN",
      "latitude": "52.9399",
      "longitude": "73.5491"
    },
    "deliveryAddress": {
      "address": "Chicago, USA",
      "latitude": "41.8781",
      "longitude": "87.6298"
    },
    "valuePerItem": "46",
    "totalOrderValue": "126500",
    "freightChargeTerms": "Freight Prepaid",
    "expectedDeliveryDates": "12-APR-2020",
    "comments": ""
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2020-04-26T20:14:44Z",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..LFKayh8S3hxHc2hZJP-ARH6qZO06pBUJgPg9osvH2OD-OftB-SvIv3Tni_j0fVwK5iYWfChAs8Cvw-czQ2S1Dw",
    "proofPurpose": "assertionMethod",
    "verificationMethod": "did:v1:test:nym:z6MkfG5HTrBXzsAP8AbayNpG3ZaoyM4PCqNPrdWQRSpHDV6J#z6MkqfvdBsFw4QdGrZrnx7L1EKfY5zh9tT4gumUGsMMEZHY3"
  }
}
```

produces an error because of the mapping:
```
"comments": "schema:text"
```
in https://mavennet.github.io/contexts/bill-of-lading-v1.0.jsonld

### PR DESCRIPTION
**Pull request by kdimak**
closes #1781

Signed-off-by: Dmitriy Kinoshenko <dkinoshenko@gmail.com>

### CODE REVIEW

**Comment by rolsonquadras** [comment]
@kdimak unit tests is failing - https://github.com/hyperledger/aries-framework-go/pull/1782/checks?check_run_id=646744185

FAIL: TestNewCredentialFromLinkedDataProof_JSONLD_Validation/VC_with_different_mapped_field (5.03s)
        credential_ldp_test.go:263: 
            	Error Trace:	credential_ldp_test.go:263
            	Error:      	Received unexpected error:
            	            	JSON-LD doc has different structure after compaction
            	Test:       	TestNewCredentialFromLinkedDataProof_JSONLD_Validation/VC_with_different_mapped_field

File: pkg/doc/verifiable/jsonld.go [hunk 1]
```diff
@@ -294,7 +294,39 @@ func compactJSONLD(doc string, opts *jsonldCredentialOpts, strict bool) error {
...
+		}
+
+		v2, present := compacted[k]
+		if !present { // special case - the name of the map was mapped, cannot guess what's a new name
+			continue
+		}
+
+		v2Map, isMap := v2.(map[string]interface{})
+		if !isMap {
+			return false
```
Comment (rolsonquadras) [inline pkg/doc/verifiable/jsonld.go:321]: This will fail when higher level values are scalar. like id, issuer.

Comment (kdimak) [reply pkg/doc/verifiable/jsonld.go:321]: Yeah, i made lint happy and introduced one unintentional bug. It should be `!isMap` check at line 310, then we just make sure that we compare two maps
