### PR TITLE
fix: date-time format in "default" JSON VC schema.

### LINKED ISSUE #967: Fix date-time format in "default" JSON VC schema.
The JSON schema for verifiable credentials is currently too strict for date/time processing. Instead of a custom regular expression, the date/time format of the parser library should be used. Example:

 ```
"issuanceDate": {
"type": "string",
   "format": "date-time"
 },
```

### PR DESCRIPTION
**Pull request by kdimak**
closes #967

Signed-off-by: Dima <dkinoshenko@gmail.com>

### CODE REVIEW

File: pkg/doc/verifiable/credential_test.go [hunk 1]
```diff
@@ -121,31 +121,34 @@ func TestNewCredential(t *testing.T) {
...
 	t.Run("test verifiable credential with empty context", func(t *testing.T) {
-		raw := &rawCredential{}
+		var raw rawCredential
+
 		require.NoError(t, json.Unmarshal([]byte(validCredential), &raw))
 		raw.Context = nil
 		bytes, err := json.Marshal(raw)
 		require.NoError(t, err)
-		err = validate(bytes, nil, &credentialOpts{disabledCustomSchema: true})
+		err = validate(bytes, nil, &credentialOpts{})
```
Comment (llorllale) [inline pkg/doc/verifiable/credential_test.go]: @troyronda pointed this out in the chat: why was this changed?

Comment (kdimak) [reply pkg/doc/verifiable/credential_test.go]: It was just a redundant setting of the parameter. The majority of validation tests pass regardless of `disabledCustomSchema` option value.
