### PR TITLE
fix: mysql storage tests are not properly waiting for db readiness

### LINKED ISSUE #2051: mysql storage: tests are not properly waiting for db readiness
https://github.com/hyperledger/aries-framework-go/blob/e4ed522212cb5a4f49eeb06f2c9e882aa389cb60/pkg/storage/mysql/mysqlstore_test.go#L37

The check performed by `checkMySQL()` is insufficient - it needs to also call `db.Ping()` and make sure it succeeds. It should also do an appropriate number of retries.

Afterwards, if `checkMySQL()` fails then the exit code in `TestMain` MUST be something other than `0`.

### PR DESCRIPTION
**Pull request by talwinder50**
closes #2051

Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>

### CODE REVIEW

File: pkg/storage/mysql/mysqlstore_test.go [hunk 1]
```diff
@@ -12,7 +12,9 @@ import (
 	"os"
 	"strings"
 	"testing"
+	"time"
 
+	"github.com/cenkalti/backoff"
```
Comment (troyronda) [inline pkg/storage/mysql/mysqlstore_test.go:17]: should be using `github.com/cenkalti/backoff/v4` - this version has go module support.

File: go.mod [hunk 2]
```diff
@@ -8,6 +8,7 @@ require (
 	github.com/VictoriaMetrics/fastcache v1.5.7
 	github.com/btcsuite/btcd v0.20.1-beta
 	github.com/btcsuite/btcutil v1.0.1
+	github.com/cenkalti/backoff v2.2.1+incompatible
```
Comment (troyronda) [inline go.mod:11]: should be using the version that has go module support. see below.

File: pkg/storage/mysql/mysqlstore_test.go (hunk 1 above)
Comment (talwinder50) [reply pkg/storage/mysql/mysqlstore_test.go]: @troyronda updated
