### PR TITLE
bug: remove nolint gosec and fix possible sql injection vulnerability

### LINKED ISSUE #1952: bug: remove nolint gosec and fix possible sql injection attack
current mysql storage implementation injects the storage as a free form string in the SQL queries.

golint sec has been wrongly disabled on these queries.

Remove the nolint gosec comments and fix the storage name in the statements to be added as part of the prepared statement.

### PR DESCRIPTION
**Pull request by Baha-sk**
closes #1952

Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

### CODE REVIEW

File: pkg/storage/mysql/mysqlstore.go [hunk 1]
```diff
@@ -149,10 +149,10 @@ func (s *sqlDBStore) Put(k string, v []byte) error {
 		return storage.ErrKeyRequired
 	}
 
-	//nolint: gosec create upsert query to insert the record, checking whether the key is already mapped to a value in the store.
-	createStmt := "INSERT INTO " + s.tableName + " VALUES (?, ?) ON DUPLICATE KEY UPDATE value=?"
+	// create upsert query to insert the record, checking whether the key is already mapped to a value in the store.
+	createStmt := "INSERT INTO ? VALUES (?, ?) ON DUPLICATE KEY UPDATE value=?"
```
Comment (llorllale) [inline pkg/storage/mysql/mysqlstore.go:153]: @talwinder50

Comment (talwinder50) [reply pkg/storage/mysql/mysqlstore.go:153]: https://github.com/go-sql-driver/mysql/issues/848

I have already tried This query wont work see the spec they dont support placeholders on table name they only support on where and like. If we run this against the real mysql it will throw syntax error

Comment (llorllale) [reply pkg/storage/mysql/mysqlstore.go:153]: @talwinder50 thanks. Looks like we need to rollback this PR....
