### PR TITLE
fix: Query connection not returning transient data

### LINKED ISSUE #722: RestAPI Query connection doesn't return in-progress connection
The QueryConnectionsAPI doesn't return in-progress connections. The GetConnection API returns in-progress connections. This is due to the change of db structure into transient v permanent. In case of query connections, the data is only read from [permanent store](https://github.com/hyperledger/aries-framework-go/blob/master/pkg/didcomm/protocol/didexchange/persistence.go#L139).

### PR DESCRIPTION
**Pull request by rolsonquadras**
- Add transient db search in query connection function
- Implement iterator in mem storage

Closes #722 

Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

### CODE REVIEW

File: pkg/didcomm/protocol/didexchange/persistence_test.go [hunk 1]
```diff
@@ -368,21 +369,37 @@ func TestConnectionRecorder_SaveNSThreadID(t *testing.T) {
...
 	t.Run("test query connection record", func(t *testing.T) {
 		store := &mockstorage.MockStore{Store: make(map[string][]byte)}
-		const count = 5
-		for i := 0; i < count; i++ {
-			val, err := json.Marshal(&ConnectionRecord{
+
+		transientStore, err := mem.NewProvider().OpenStore(DIDExchange)
+		require.NoError(t, err)
+
+		const storeCount = 5
```
Comment (troyronda) [inline pkg/didcomm/protocol/didexchange/persistence_test.go]: suggest a const block.

Comment (rolsonquadras) [reply pkg/didcomm/protocol/didexchange/persistence_test.go]: [Done](https://github.com/hyperledger/aries-framework-go/compare/34dade7a79ff4c996b1c0d8c2ccf3ef04fc37320..6baf0c5e8a819feab5eda58438c093ba60eb3f4f#diff-d27598adea2d2cee7ff4fd55d2b9481bR376).

File: pkg/didcomm/protocol/didexchange/persistence.go [hunk 2]
```diff
@@ -140,6 +141,8 @@ func (c *ConnectionRecorder) QueryConnectionRecords() ([]*ConnectionRecord, erro
 	defer itr.Release()
 
 	var records []*ConnectionRecord
+	// TODO https://github.com/hyperledger/aries-framework-go/issues/655 -- Update map size based on pagination limit
+	keys := make(map[string]struct{}, 100)
```
[the remark this answers is not in the document]
Comment (rolsonquadras) [reply pkg/didcomm/protocol/didexchange/persistence.go]: [Removed](https://github.com/hyperledger/aries-framework-go/compare/6baf0c5e8a819feab5eda58438c093ba60eb3f4f..a6d9e4491d6a9de8667c5193789ccb6d8f784266#diff-74afb23b9e856cf6057416c69199df70R145).
