### PR TITLE
fix: keyResolverAdapter id

### LINKED ISSUE #1195: fix keyResolverAdapter

### PR DESCRIPTION
**Pull request by fqutishat**
closes #1195

Signed-off-by: Firas Qutishat <firas.qutishat@securekey.com>

### CODE REVIEW

File: pkg/doc/verifiable/common.go [hunk 1]
```diff
@@ -49,14 +49,14 @@ func (ja JWSAlgorithm) jose() (jose.SignatureAlgorithm, error) {
 	}
 }
 
-// PublicKeyFetcher fetches public key for JWT signing verification based on Issuer ID (possibly DID)
+// PublicKeyFetcher fetches public key for JWT signing verification based on DID
 // and Key ID.
 // If not defined, JWT encoding is not tested.
-type PublicKeyFetcher func(issuerID, keyID string) (interface{}, error)
+type PublicKeyFetcher func(did, keyID string) (interface{}, error)
```
Comment (troyronda) [inline pkg/doc/verifiable/common.go]: I'm a bit confused by this change. Is this a DID specific interface or a generic one for keys?

File: pkg/doc/verifiable/common.go [hunk 2]
```diff
@@ -49,14 +49,14 @@ func (ja JWSAlgorithm) jose() (jose.SignatureAlgorithm, error) {
...
 
 // SingleKey defines the case when only one verification key is used and we don't need to pick the one.
 func SingleKey(pubKey interface{}) PublicKeyFetcher {
-	return func(issuerID, keyID string) (interface{}, error) {
+	return func(did, keyID string) (interface{}, error) {
```
Comment (troyronda) [inline pkg/doc/verifiable/common.go]: similar here.
