### PR TITLE
fix: loading raw pub key to Tink keyset.Handle fails verification

### LINKED ISSUE #1483: invalid public key by localkms.ExportPubKeyBytes()
Public key export doing by `localkms.ExportPubKeyBytes()` doesn’t seem to do a full extract of the public key.

How to check: extend `TestLocalKMS_Success`, test signing/verification using `tinkcrypto`:
```
if strings.Contains(string(v), "ECDSA") || v == kms.Ed25519Type {
	pubKeyBytes, e := kmsService.ExportPubKeyBytes(keyID)
	require.Errorf(t, e, "KeyID has been rotated. An error must be returned")
	require.Empty(t, pubKeyBytes)

	pubKeyBytes, e = kmsService.ExportPubKeyBytes(newKeyID)
	require.NoError(t, e)
	require.NotEmpty(t, pubKeyBytes)

	kh, e := kmsService.PubKeyBytesToHandle(pubKeyBytes, v)
	require.NoError(t, e)
	require.NotEmpty(t, kh)

	// NEW: verify the restored public key
	c, err := tinkcrypto.New()
	require.NoError(t, err)

	msg := []byte("test message")

	msgSig, err := c.Sign(msg, newKeyHandle)
	require.NoError(t, err)

	err = c.Verify(msgSig, msg, kh)
	require.NoError(t, err)
}

```

### PR DESCRIPTION
**Pull request by Baha-sk**
Since default signing key templates have Tink specific prefix,
need to use RAW type to avoid adding a prefix. This will fix
verification with a keyset.Handle created from raw public key []byte

To unblock dev, the temporary fix is to manually change the key templates
in aries-framework-go code. A followup issue is created to use Tink
created key templates without a prefix when the templates are
available in Tink (#1489).

closes #1483

Signed-off-by: Baha Shaaban <baha.shaaban@securekey.com>

### CODE REVIEW

**Comment by kdimak** [comment]
@Baha-sk  can we add a test case I mentioned at https://github.com/hyperledger/aries-framework-go/issues/1483#issue-583803837 to double-check your temporary fix?

**Comment by Baha-sk** [comment]
> @Baha-sk can we add a test case I mentioned at [#1483 (comment)](https://github.com/hyperledger/aries-framework-go/issues/1483#issue-583803837) to double-check your temporary fix?

@kdimak the test already exists: https://github.com/hyperledger/aries-framework-go/blob/master/pkg/kms/localkms/pubkey_export_import_test.go#L76

**Comment by kdimak** [comment]
> > @Baha-sk can we add a test case I mentioned at [#1483 (comment)](https://github.com/hyperledger/aries-framework-go/issues/1483#issue-583803837) to double-check your temporary fix?
> 
> @kdimak the test already exists: https://github.com/hyperledger/aries-framework-go/blob/master/pkg/kms/localkms/pubkey_export_import_test.go#L76

OK!

File: pkg/kms/localkms/pubkey_export_import_test.go [hunk 1]
```diff
@@ -78,7 +96,7 @@ func TestPubKeyExportAndRead(t *testing.T) {
 				require.NotEmpty(t, verifier)
 
 				err = verifier.Verify(s, msg)
-				require.NotEmpty(t, err)
+				require.NoError(t, err)
```
Comment (Baha-sk) [inline pkg/kms/localkms/pubkey_export_import_test.go]: this fixes the current verification test... it was wrongly checking if err is not empty, instead of checking if there's no error
