### PR TITLE
fix: linter to include bdd tests

### LINKED ISSUE #738: linter not running on bdd packages
fix it

### PR DESCRIPTION
**Pull request by sudeshrshetty**
- closes #738

Signed-off-by: sudesh.shetty <sudesh.shetty@securekey.com>

### CODE REVIEW

File: scripts/check_lint.sh [hunk 1]
```diff
@@ -17,3 +17,4 @@ fi
 
 ${DOCKER_CMD} run --rm -e GOPROXY=${GOPROXY} -v $(pwd):/opt/workspace -w /opt/workspace golangci/golangci-lint:v1.21 golangci-lint run
 ${DOCKER_CMD} run --rm -e GOPROXY=${GOPROXY} -v $(pwd):/opt/workspace -w /opt/workspace/cmd/aries-agentd golangci/golangci-lint:v1.21 golangci-lint run -c ../../.golangci.yml
+${DOCKER_CMD} run --rm -e GOPROXY=${GOPROXY} -v $(pwd):/opt/workspace -w /opt/workspace/test/bdd golangci/golangci-lint:v1.21 golangci-lint run -c ../../.golangci.yml
```
Comment (troyronda) [inline scripts/check_lint.sh]: It would be nice to use a variable for the linter version - we have now repeated on three lines.
