### PR TITLE
fix: aries-js-worker notifier to follow REST notifier behavior

### LINKED ISSUE #1259: Aries JW Worker notifier to match Aries REST notifier

### PR DESCRIPTION
**Pull request by sudeshrshetty**
- use `aries.waitForNotification()` to subscribe for all the topics
- use `aries.waitForNotification(topics)` to subscribe by topics.
- removed "notifier-func-name" from aries start opts.
- closes #1259

Signed-off-by: sudesh.shetty <sudesh.shetty@securekey.com>

### CODE REVIEW

File: cmd/aries-js-worker/main.go [hunk 1]
```diff
@@ -219,7 +217,7 @@ func handlerNotFoundErr(c *command) *result {
 		return newErrResult(c.ID, "Aries agent not running")
 	}
 
-	return newErrResult(c.ID, fmt.Sprintf("invalid pkg/fn: %s/%s", c.Pkg, c.Fn))
+	return newErrResult(c.ID, fmt.Sprintf("invalid pkg/fn: %s/%s, make sure aries is stated", c.Pkg, c.Fn))
```
Comment (rolsonquadras) [inline cmd/aries-js-worker/main.go]: stated - typo ?

Comment (sudeshrshetty) [reply cmd/aries-js-worker/main.go]: done
