### PR TITLE
fix: do not fire didexchange event after accepting oob message

### LINKED ISSUE #1814: outofband: user should not have to approve did-exchange after accepting an out-of-band request or invitation

### PR DESCRIPTION
**Pull request by llorllale**
closes #1814

Note: `presentproof_sdk_steps.go#acceptRequestPresentation` was refactored because the JWS signature verification was failing for an as-yet unclear reason. Some of this method's assumptions[1] were strange to me, so I refactored and it started working. Please take a look.

[1]: it was assuming the first connection record retrieved from an agent's storage was the right one, and it was assuming consistency between these connection records and public DIDs registered in the BDD context by a different BDD package

Signed-off-by: George Aristy <george.aristy@securekey.com>

### CODE REVIEW

File: pkg/client/outofband/client.go [hunk 1]
```diff
@@ -35,6 +35,18 @@ const (
 	InvitationMsgType = outofband.InvitationMsgType
 )
 
+// EventOptions are is a container of options that you can pass to an event's
+// Continue function to customize the reaction to incoming out-of-band messages.
+type EventOptions struct {
+	// Label will be shared with the other agent during the subsequent did-exchange.
```
Comment (troyronda) [inline pkg/client/outofband/client.go:41]: Do you have thoughts about this coupling? We don't know that the subsequent action will be a DID exchange right?

Comment (llorllale) [reply pkg/client/outofband/client.go:41]: It can be any protocol that forms a connection, really. Or it can be an ephemeral mode.

File: pkg/client/outofband/client.go [hunk 2]
```diff
@@ -56,10 +68,10 @@ type message struct {
 
 type oobService interface {
 	service.Event
-	AcceptRequest(request *outofband.Request) (string, error)
-	AcceptInvitation(inv *outofband.Invitation) (string, error)
-	SaveRequest(request *outofband.Request) error
-	SaveInvitation(inv *outofband.Invitation) error
+	AcceptRequest(*outofband.Request, string) (string, error)
```
Comment (troyronda) [inline pkg/client/outofband/client.go:71]: Will this function signature be stable, or is there the possibility of more arguments? 

Since there is an `EventOptions` struct above, should there be some struct parameter here?

File: pkg/client/outofband/client.go (hunk 1 above)
Comment (troyronda) [reply pkg/client/outofband/client.go:41]: So is Label intended to be generic or about did-exchange?

I would like to avoid this struct becoming a collection of all possible followup options. In that case, it seems better to pass options directly into the followup protocol implementation.

File: pkg/client/outofband/client.go (hunk 2 above)
Comment (llorllale) [reply pkg/client/outofband/client.go:71]: I can't comment on its stability. I was following similar patterns in the didexchange client package.

Comment (troyronda) [reply pkg/client/outofband/client.go:71]: My concern stems more from this same theme: https://github.com/hyperledger/aries-framework-go/pull/1815#discussion_r423708740

(there could be other followup protocols).
