### PR TITLE
fix: fix panic in case of parsing null did document

### LINKED ISSUE #1430: Got panic in case of parsing null as did document
**What I'm trying to do**

I'm parsing "null" string by did.ParseDocument

**Expected result**

I'm getting nil, error or empty struct.

**Actual result**

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13e8130]

goroutine 6 [running]:
testing.tRunner.func1(0xc000154400)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:874 +0x3a3
panic(0x1464900, 0x18609c0)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
github.com/hyperledger/aries-framework-go/pkg/doc/did.ParseDocument(0xc0001ba818, 0x4, 0x4, 0xc000042760, 0x1083c26, 0x5e625ca9)
	/Users/belezeko/Projects/aries-framework-go/pkg/doc/did/doc.go:401 +0x1a0
github.com/hyperledger/aries-framework-go/pkg/doc/did.TestParseOfNull(0xc000154400)
	/Users/belezeko/Projects/aries-framework-go/pkg/doc/did/doc_test.go:144 +0x57
testing.tRunner(0xc000154400, 0x1503b48)
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/Cellar/go/1.13.4/libexec/src/testing/testing.go:960 +0x350

Process finished with exit code 1
```

**Sample code / test case**

```
func TestParseOfNull(t *testing.T) {
	doc, err := ParseDocument([]byte("null"))
	require.NoError(t, err)
	require.Nil(t, doc)
}
```

### PR DESCRIPTION
**Pull request by AlexeyBelezeko**
Signed-off-by: Aleksei Belezeko <aleksei.belezeko@t-systems.com>

I found a bug that Parse Document get panic in case of null string. Now it returns nil in case of null string.

Closes #1430

### CODE REVIEW

File: pkg/doc/did/doc.go [hunk 1]
```diff
@@ -396,6 +396,8 @@ func ParseDocument(data []byte) (*Doc, error) {
 	err := json.Unmarshal(data, &raw)
 	if err != nil {
 		return nil, fmt.Errorf("JSON marshalling of did doc bytes bytes failed: %w", err)
+	} else if raw == nil {
+		return nil, nil
```
Comment (soluchok) [inline pkg/doc/did/doc.go]: We cannot return `nil, nil`. It can be  `&Doc{},nil` or `nil,err`.
We have a method `validate`. I guess this check should be filtered.
there @troyronda @llorllale What do you think?

Could you please attach the panic error you got?

Comment (AlexeyBelezeko) [reply pkg/doc/did/doc.go]: Thank you for quick response. I've created issue with the panic error.

File: pkg/doc/did/doc_test.go [hunk 2]
```diff
@@ -140,6 +140,12 @@ const creator = did + "#key-1"
 const keyType = "Ed25519VerificationKey2018"
 const signatureType = "Ed25519Signature2018"
 
+func TestParseOfNull(t *testing.T) {
+	doc, err := ParseDocument([]byte("null"))
+	require.NoError(t, err)
```
Comment (llorllale) [inline pkg/doc/did/doc_test.go]: for sure there should be an error here.

File: pkg/doc/did/doc.go (hunk 1 above)
Comment (soluchok) [reply pkg/doc/did/doc.go]: Here is my suggestion. You need to change the `validate` function as I did below:

```
	var r *rawDoc
	if err := json.Unmarshal(data, &r); err != nil {
		return fmt.Errorf("unmarshal failed: %w", err)
	}

	if r == nil {
		return fmt.Errorf("document payload is not provided")
	}
```

Comment (AlexeyBelezeko) [reply pkg/doc/did/doc.go]: Done.

Comment (soluchok) [reply pkg/doc/did/doc.go]: You can do even better. I see that `validate` and `ParseDocument` functions are doing the same job. They both do `json.Unmarshal`  into `rawDoc`. It would be nice to improve optimize that by pass `rawDoc` to the  `validate` function. If `rawDoc` is provided - ignore `Unmarshal`.

Comment (soluchok) [reply pkg/doc/did/doc.go]: e.g 
```
func validate(data []byte, r *rawDoc) error {
	if r == nil {
		if err := json.Unmarshal(data, &r); err != nil {
			return fmt.Errorf("unmarshal failed: %w", err)
		}
	}

	if r == nil {
		return errors.New("document payload is not provided")
	}
```
and

```
func ParseDocument(data []byte) (*Doc, error) {
	var raw *rawDoc

	err := json.Unmarshal(data, &raw)
	if err != nil {
		return nil, fmt.Errorf("JSON marshalling of did doc bytes bytes failed: %w", err)
	}

	// validate did document
	if err := validate(data, raw); err != nil {
		return nil, err
	}
```

File: pkg/doc/did/doc.go [hunk 3]
```diff
@@ -386,16 +386,17 @@ type Proof struct {
...
 	raw := &rawDoc{}
 
 	err := json.Unmarshal(data, &raw)
 	if err != nil {
 		return nil, fmt.Errorf("JSON marshalling of did doc bytes bytes failed: %w", err)
+	} else if raw == nil {
+		return nil, errors.New("document payload is not provided")
+	}
+	// validate did document
+	if err := validate(data, raw.schemaLoader()); err != nil {
```
Comment (Baha-sk) [inline pkg/doc/did/doc.go]: replace the above line with:
```
err = validate(data, raw.schemaLoader())
if err != nil {
```
to remove the govet error

Comment (AlexeyBelezeko) [reply pkg/doc/did/doc.go]: Done

File: pkg/doc/did/doc_test.go (hunk 2 above)
Comment (AlexeyBelezeko) [reply pkg/doc/did/doc_test.go]: Done

File: pkg/doc/did/doc.go (hunk 1 above)
Comment (AlexeyBelezeko) [reply pkg/doc/did/doc.go]: Done

**Comment by llorllale** [comment]
hi @AlexeyBelezeko 

Can you please squash your commits?

Thanks!

**Comment by AlexeyBelezeko** [comment]
@llorllale squashed
