### PR TITLE
fix: Spool mysql instead of using mock

### LINKED ISSUE #1948: followup issues from PR #1938
Priority:
- [x] use prepared statements to guard against sql injection: https://github.com/hyperledger/aries-framework-go/pull/1938/files#diff-5c03fdd2a42c9a160e4a9b056cb9db20R92 #1953
- [ ] open a new `sql.DB` and exec the "USE" statement on that one. Assign it to the `storage.Store`: https://github.com/hyperledger/aries-framework-go/pull/1938/files#diff-5c03fdd2a42c9a160e4a9b056cb9db20R102
- [ ]  handle keys of arbitrary lengths: mysql throws an error on attempts to create indexes (primary keys included) on columns with a width over the configured threshold
- [ ]  sqlDBResultsIterator.Key() and Value() are advancing the SQL rows cursor independendently
- [ ]  mocking the database in tests

Lower:

* no need to open an `sql.Trx` in `OpenStore()`
* sqlDBResultsIterator.store is unused

### PR DESCRIPTION
**Pull request by talwinder50**
Right now, sql store unit test are using sql mock : https://github.com/DATA-DOG/go-sqlmock 
As per the discussion with the team, seems like its not so viable option to choose. Therefore, update the the unit-test to use the mysql db instead of mock. 

Fix the below from the list 1948: 
- open a new sql.DB and exec the "USE" statement on that one. Assign it to the storage.Store: https://github.com/hyperledger/aries-framework-go/pull/1938/files#diff-5c03fdd2a42c9a160e4a9b056cb9db20R102
- mocking the database in tests

closes #1948 

Signed-off-by: talwinder.kaur <talwinder.kaur@securekey.com>

### CODE REVIEW

File: pkg/storage/mysql/mysqlstore.go [hunk 1]
```diff
@@ -70,19 +70,20 @@ func (p *Provider) OpenStore(name string) (storage.Store, error) {
 	p.Lock()
 	defer p.Unlock()
 
-	tx, err := p.db.Begin()
+	// creating the database
+	_, err := p.db.Exec(createDBQuery + name)
```
Comment (Baha-sk) [inline pkg/storage/mysql/mysqlstore.go:74]: verify name is not empty

Comment (talwinder50) [reply pkg/storage/mysql/mysqlstore.go:78]: done

**Comment by soluchok** [comment]
@talwinder50 Could you please use this package for testing https://github.com/ory/dockertest

**Comment by talwinder50** [comment]
> @talwinder50 Could you please use this package for testing https://github.com/ory/dockertest

@soluchok  As we tried #1964 doest fix the  Could not start resource: : dial unix /var/run/docker.sock: connect: no such file or directory error in the CI  for using docker test. i followed the already existing pattern and CI pass.
