### PR TITLE
fix: omit empty credential schema in marshalled credential

### LINKED ISSUE #1627: Marshalled credential should omit empty credential schema
currently we include `"credentialSchema": []` in our marshalled JSON of Credential.

### PR DESCRIPTION
**Pull request by sudeshrshetty**
- Closes #1627

Signed-off-by: sudesh.shetty <sudesh.shetty@securekey.com>

### CODE REVIEW

**Comment by kdimak** [comment]
LGTM

File: pkg/doc/verifiable/credential_test.go [hunk 1]
```diff
@@ -1639,3 +1639,40 @@ func TestNewUnverifiedCredential(t *testing.T) {
...
 }
+
+func TestMarshalCredential(t *testing.T) {
+	t.Run("test marshalling VC to JSON bytes", func(t *testing.T) {
+		vc, vcData, err := NewCredential([]byte(validCredential))
+		require.NoError(t, err)
+		require.NotNil(t, vc)
+		require.NotEmpty(t, vcData)
+
+		getvcMap := func(t *testing.T, vc *Credential) map[string]interface{} {
```
Comment (kdimak) [inline pkg/doc/verifiable/credential_test.go:1650]: You can use `toMap()` function from this package instead of `getvcMap()`

Comment (sudeshrshetty) [reply pkg/doc/verifiable/credential_test.go]: done
