### PR TITLE
fix: proofPurpose not used for credentials and presentations

### LINKED ISSUE #1578: 'proofPurpose' not used for credentials and presentations
Looks like proofPurpose is not set while creating proof for VCs and VPs.(should be default "assertionMethod").

This is causing interop issue in thridparty systems where proof digest is included (default if missing) during signature verifications.

### PR DESCRIPTION
**Pull request by kdimak**
closes #1578

Signed-off-by: Dmitriy Kinoshenko <dkinoshenko@gmail.com>

We put default `assertionMethod` into `proofPurpose`. At the follow-up issue https://github.com/hyperledger/aries-framework-go/issues/1586 we need to support it fully.

### CODE REVIEW

File: pkg/doc/signature/signer/signer.go [hunk 1]
```diff
@@ -102,6 +104,7 @@ func (signer *DocumentSigner) signObject(context *Context, jsonLdObject map[stri
 		Domain:                  context.Domain,
 		Nonce:                   context.Nonce,
 		VerificationMethod:      context.VerificationMethod,
+		ProofPurpose:            defaultProofPurpose,
```
Comment (troyronda) [inline pkg/doc/signature/signer/signer.go:107]: should have TODO.

Comment (sudeshrshetty) [inline pkg/doc/signature/signer/signer.go:107]: There is also one more place where we call "NewProof()", shouldn't we use default there too?

Comment (kdimak) [reply pkg/doc/signature/signer/signer.go:107]: It's the place where we roughly speaking unmarshal `Proof`. So we should leave existent assignment:
```
ProofPurpose:            stringEntry(emap[jsonldProofPurpose]),
```

Comment (kdimak) [reply pkg/doc/signature/signer/signer.go]: added
