### PR TITLE
fix: Integrate route service with SendToDID function

### LINKED ISSUE #1061: DIDComm Route Service - Connection details TODO fix
DIDComm Route Service - Connection details TODO fix 
https://github.com/hyperledger/aries-framework-go/blob/41ea60bef355226f45d9ac95c04af4b862746619/pkg/didcomm/protocol/route/service.go#L188
https://github.com/hyperledger/aries-framework-go/blob/41ea60bef355226f45d9ac95c04af4b862746619/pkg/didcomm/protocol/route/service.go#L220
https://github.com/hyperledger/aries-framework-go/blob/41ea60bef355226f45d9ac95c04af4b862746619/pkg/didcomm/protocol/route/service.go#L256
https://github.com/hyperledger/aries-framework-go/blob/41ea60bef355226f45d9ac95c04af4b862746619/pkg/didcomm/protocol/route/service.go#L290

### PR DESCRIPTION
**Pull request by rolsonquadras**
Closes #1061 

Signed-off-by: Rolson Quadras <rolson.quadras@securekey.com>

### CODE REVIEW

File: pkg/didcomm/protocol/route/service.go [hunk 1]
```diff
@@ -253,8 +255,7 @@ func (s *Service) handleKeylistUpdate(msg *service.DIDCommMsg) error {
 		Updated: updates,
 	}
 
-	// TODO https://github.com/hyperledger/aries-framework-go/issues/725 get destination details from the connection
-	return s.outbound.Send(updateResponse, "", nil)
+	return s.outbound.SendToDID(updateResponse, myDID, theirDID)
```
Comment (sudeshrshetty) [inline pkg/didcomm/protocol/route/service.go]: is it always SendToDID?

Comment (rolsonquadras) [reply pkg/didcomm/protocol/route/service.go]: Yes.
