### PR TITLE
fix: VC data model and JWT to pass the test suite

### LINKED ISSUE #358: Fix Verifiable Credential data model and JWT to pass the Verifiable Claims WG Test Suite

### PR DESCRIPTION
**Pull request by kdimak**
closes #358

Signed-off-by: Dima <dkinoshenko@gmail.com>

VC Test Suite statistics:
- 57 passing
- 19 pending
- 18 failing

The reasons for failing:
- JWT suite errors, ES256K support required (#381 )
- Cannot generate JWT from Verifiable Credential without the signature (#372 )
- Support of Verifiable Presentation (#371 )
- Several inconsistencies in VC Test Suite: [#96](https://github.com/w3c/vc-test-suite/issues/96), [#97](https://github.com/w3c/vc-test-suite/issues/97), [#98](https://github.com/w3c/vc-test-suite/issues/98)

The reasons for pending:
- Not implemented support of Zero Knowledge Proof (#180 ), `zkp` test suite is disabled for now.

### CODE REVIEW

File: pkg/doc/verifiable/credential.go [hunk 1]
```diff
@@ -562,20 +699,20 @@ func describeSchemaValidationError(result *gojsonschema.Result) string {
...
 func getCredentialSchema(schema *CredentialSchema, opts *credentialOpts) (gojsonschema.JSONLoader, error) {
-	schemaLoader := defaultSchemaLoader
 	if schema != nil && !opts.disabledCustomSchema {
 		switch schema.Type {
 		case jsonSchema2018Type:
-			if customSchemaData, err := loadCredentialSchema(schema.ID, opts.schemaDownloadClient); err == nil {
-				schemaLoader = gojsonschema.NewBytesLoader(customSchemaData)
-			} else {
-				return nil, fmt.Errorf("loading custom credential schema from %s failed: %w", schema.ID, err)
+			var err error
```
Comment (troyronda) [inline pkg/doc/verifiable/credential.go]: this line can (and should be eliminated if you change L707 to not embed the if condition (and instead create a line after).

File: pkg/doc/verifiable/credential.go [hunk 2]
```diff
@@ -562,20 +699,20 @@ func describeSchemaValidationError(result *gojsonschema.Result) string {
...
+			var customSchemaData []byte
+			if customSchemaData, err = loadCredentialSchema(schema.ID, opts.schemaDownloadClient); err == nil {
```
Comment (troyronda) [inline pkg/doc/verifiable/credential.go]: if err != nil is usually first.

File: pkg/doc/verifiable/credential.go (hunk 1 above)
Comment (kdimak) [reply pkg/doc/verifiable/credential.go]: Yeah, my stupid miss.

File: pkg/doc/verifiable/credential.go (hunk 2 above)
Comment (kdimak) [reply pkg/doc/verifiable/credential.go]: OK!

File: pkg/doc/verifiable/credential.go [hunk 3]
```diff
@@ -562,20 +699,19 @@ func describeSchemaValidationError(result *gojsonschema.Result) string {
...
+			if err != nil {
 				return nil, fmt.Errorf("loading custom credential schema from %s failed: %w", schema.ID, err)
 			}
+			return gojsonschema.NewBytesLoader(customSchemaData), nil
 		default:
 			logger.Warnf("unsupported credential schema: %s. Using default schema for validation", schema.Type)
 		}
 	}
-	return schemaLoader, nil
+	return nil, nil
```
Comment (troyronda) [inline pkg/doc/verifiable/credential.go]: We shouldn't see return nil, nil

File: pkg/doc/verifiable/credential.go [hunk 4]
```diff
@@ -220,19 +268,37 @@ func (ja JWTAlgorithm) Jose() jose.SignatureAlgorithm {
...
 
+type typeSingle struct {
+	Type string `json:"type,omitempty"`
+}
+
+type typeMultiple struct {
+	Types []string `json:"type,omitempty"`
+}
+
+type credentialSchemaSingle struct {
```
Comment (troyronda) [inline pkg/doc/verifiable/credential.go]: Could you explain a bit more why you needed an extra `credentialSchemaSingle` type?

File: pkg/doc/verifiable/test-suite/verifiable_suite_test.go [hunk 5]
```diff
@@ -142,7 +150,7 @@ func parseKeys(packedKeys string) (private, public interface{}) {
 }
 
 func encodeVCToJSON(vcBytes []byte) {
-	credential, err := verifiable.NewCredential(vcBytes)
+	credential, err := verifiable.NewCredential(vcBytes, verifiable.WithNoCustomSchemaCheck())
```
Comment (troyronda) [inline pkg/doc/verifiable/test-suite/verifiable_suite_test.go]: Is there an issue?

File: pkg/doc/verifiable/credential.go (hunk 3 above)
Comment (kdimak) [reply pkg/doc/verifiable/credential.go]: Agree!

File: pkg/doc/verifiable/credential.go (hunk 4 above)
Comment (kdimak) [reply pkg/doc/verifiable/credential.go]: You are right.

File: pkg/doc/verifiable/test-suite/verifiable_suite_test.go (hunk 5 above)
Comment (kdimak) [reply pkg/doc/verifiable/test-suite/verifiable_suite_test.go]: In the Test Suite, there is a suite that checks Credential Schemas of Credential. They use fake URLs and `NewCredential()` because of that. Using `WithNoCustomSchemaCheck()`, we disable loading of custom schemas and thus get rid of the issue.

File: pkg/doc/verifiable/credential.go (hunk 3 above)
Comment (kdimak) [reply pkg/doc/verifiable/credential.go]: Refactored.

File: pkg/doc/verifiable/credential.go [hunk 6]
```diff
@@ -561,21 +687,26 @@ func describeSchemaValidationError(result *gojsonschema.Result) string {
 	return errMsg
 }
 
-func getCredentialSchema(schema *CredentialSchema, opts *credentialOpts) (gojsonschema.JSONLoader, error) {
-	schemaLoader := defaultSchemaLoader
-	if schema != nil && !opts.disabledCustomSchema {
+func getSchemaLoader(schemas []CredentialSchema, opts *credentialOpts) (gojsonschema.JSONLoader, error) {
```
Comment (troyronda) [inline pkg/doc/verifiable/credential.go]: Just double checking that it was intentional to remove the pointer type.
i.e., you have []CredentialSchema rather than []*CredentialSchema.

Comment (kdimak) [reply pkg/doc/verifiable/credential.go]: Sure, Troy. Previously, `getCredentialSchema()` got Schema Loader for single credential schema, now it gets the same for the first found appropriate schema. So it's correct here.

Comment (troyronda) [reply pkg/doc/verifiable/credential.go]: Sure - agree that a slice is needed. I was more curious about the pointer type inside.

**Comment by llorllale** [comment]
@kdimak @troyronda can we add this check to the CI?

File: pkg/doc/verifiable/credential.go [hunk 7]
```diff
@@ -655,21 +786,46 @@ func (vc *Credential) JWT(signatureAlg JWTAlgorithm, privateKey interface{}, key
...
-		return "", fmt.Errorf("failed to sign JWT")
+		return "", fmt.Errorf("failed to sign JWT: %w", err)
 	}
 
 	return rawJWT, nil
 }
 
-func (vc *Credential) getFirstSubjectID() string {
+// FirstSubjectID gets ID of first subject if present or return empty string otherwise
+func (vc *Credential) FirstSubjectID() string {
```
Comment (llorllale) [inline pkg/doc/verifiable/credential.go]: This function shouldn't exist at all. If the JSON-LD VC contains multiple subjects, the `JWT()` method should return an error indicating as such.

**Comment by troyronda** [comment]
> @kdimak @troyronda can we add this check to the CI?

This test doesn't fully pass yet. I think we should create a separate test suites job (and suppress the failure flag on it for now.)

File: pkg/doc/verifiable/test-suite/config.json [hunk 8]
```diff
@@ -1,8 +1,8 @@
 {
   "generator": "aries-framework-go-gen",
-  "presentationGenerator": "aries-framework-go-gen",
+  "presentationGenerator": "aries-framework-go-gen --presentation",
```
Comment (llorllale) [inline pkg/doc/verifiable/test-suite/config.json]: `generatorOptions` is there precisely for passing parameters to the `generator` and `presentationGenerator`

**Comment by troyronda** [comment]
> > @kdimak @troyronda can we add this check to the CI?
> 
> @llorllale This test doesn't fully pass yet. I think we should create a separate test suites job (and suppress the failure flag on it for now.)

Done: https://github.com/hyperledger/aries-framework-go/pull/410

Rebase this PR to see results in the CI.

File: pkg/doc/verifiable/credential.go (hunk 7 above)
Comment (kdimak) [reply pkg/doc/verifiable/credential.go]: Agree! I will fix that.

File: pkg/doc/verifiable/test-suite/config.json (hunk 8 above)
Comment (kdimak) [reply pkg/doc/verifiable/test-suite/config.json]: On the one hand, we would like to use the same generator for both Verifiable Credential and Verifiable Presentation testing. One the other hand, we need to distinguish the processing of VC from VP in the generator. That's why I put `--presentation` there for VP.
