### PR TITLE
fix: BBS+ Selective Disclosure output fields mix

### LINKED ISSUE #2460: BBS+ Selective Disclosure output fields mix
When the input VC document has the same `id` of two fields, output BBS+ Signature Proof of VC (selective disclosure) may contain invalid substituted fields.

Exampled VC input (`issuer` and `credentialSubject` have the same `id` `did:example:b34ca6cd37bbf23`):
```
{
 "@context": [
   "https://www.w3.org/2018/credentials/v1",
   "https://w3id.org/citizenship/v1",
   "https://w3c-ccg.github.io/ldp-bbs2020/context/v1"
 ],
 "id": "https://issuer.oidp.uscis.gov/credentials/83627465",
 "type": [
   "VerifiableCredential",
   "PermanentResidentCard"
 ],
 "issuer": "did:example:b34ca6cd37bbf23",
 "identifier": "83627465",
 "name": "Permanent Resident Card",
 "description": "Government of Example Permanent Resident Card.",
 "issuanceDate": "2019-12-03T12:19:52Z",
 "expirationDate": "2029-12-03T12:19:52Z",
 "credentialSubject": {
   "id": "did:example:b34ca6cd37bbf23",
   "type": [
	 "PermanentResident",
	 "Person"
   ],
   "givenName": "JOHN",
   "familyName": "SMITH",
   "gender": "Male",
   "image": "data:image/png;base64,iVBORw0KGgokJggg==",
   "residentSince": "2015-01-01",
   "lprCategory": "C09",
   "lprNumber": "999-999-999",
   "commuterClassification": "C1",
   "birthCountry": "Bahamas",
   "birthDate": "1958-07-17"
 }
}
```

Reveal doc:
```
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/citizenship/v1",
    "https://w3c-ccg.github.io/ldp-bbs2020/context/v1"
  ],
  "type": ["VerifiableCredential", "PermanentResidentCard"],
  "@explicit": true,
  "identifier": {},
  "issuer": {},
  "issuanceDate": {},
  "credentialSubject": {
    "@explicit": true,
    "type": ["PermanentResident", "Person"],
    "givenName": {},
    "familyName": {},
    "gender": {}
  }
}
```

Invalid output (content of`credentialSubject` and `issuer` is replaced):
```
{
 "@context": [
  "https://www.w3.org/2018/credentials/v1",
  "https://w3id.org/citizenship/v1",
  "https://w3c-ccg.github.io/ldp-bbs2020/context/v1"
 ],
 "credentialSubject": "did:example:b34ca6cd37bbf23",
 "id": "https://issuer.oidp.uscis.gov/credentials/83627465",
 "identifier": "83627465",
 "issuanceDate": "2019-12-03T12:19:52Z",
 "issuer": {
  "birthCountry": "Bahamas",
  "birthDate": "1958-07-17",
  "commuterClassification": "C1",
  "familyName": "SMITH",
  "gender": "Male",
  "givenName": "JOHN",
  "id": "did:example:b34ca6cd37bbf23",
  "image": "data:image/png;base64,iVBORw0KGgokJggg==",
  "lprCategory": "C09",
  "lprNumber": "999-999-999",
  "residentSince": "2015-01-01",
  "type": [
   "Person",
   "PermanentResident"
  ]
 },
 "proof": {
  "created": "2021-01-18T17:02:11.59518+02:00",
  "nonce": "bm9uY2U=",
  "proofPurpose": "assertionMethod",
  "proofValue": "ABkBuv//sFnmOD99vfX+5p4+F+Ur0cYkOYkUU6ZYMUGvd5yd5KXgxtBuSU5hiMx2qlK5H+/zlKsIdQXxy0CVryll1wVeKio2sz0nbTQUS2RyqZZFvLZN7N6LF2hnaxQqcaGLBVQ5jC9kh4zH+MtY6BKLzAs8gUhuGp0gxJflQ1HFu659WoQjtWV+B71aSnopdnQF6N+VAAAAdJj+Vzs3aaCwcoaobTLkEgMLCzR1TBlft4+nVjzAlcMDo4wCyAviU7HBj7NM5nvdKwAAAAIF+cH9qNrfMJnTuLRBkEzPmVJbDvcodXmmwjDejmPZik+/5vA28eiixqhF5/vsMxnfxSNQ8JIXwItyevSFmalTqU3Ly7CpVBWOBiCclKp8H6rtc7FfRzGaJeog9beIkMwM9oZGakbg73vDLVLUGnxdAAAABWHb5Hdll6QtvOP+fgb8MFY62wCx8Ha1mkLjpwZPSNrZRJ+bxLmbklW4UTu2C3kLofAdJVgOhdP6+u/3NuDQ94hLe4oYWBa/lmnbgBz+8maZCT11FHUXPEH16zDGtG6L8WoI7Mu+OZP2QiaCYVvyIplbi/OkZ022puJtszrpjbroYMQA1ftEKvcnjYDvMOxF3zfK91N4Flw8L3sSSZvStnQ=",
  "type": "BbsBlsSignatureProof2020",
  "verificationMethod": "did:example:123456#key1"
 },
 "type": [
  "PermanentResidentCard",
  "VerifiableCredential"
 ]
}
```

### PR DESCRIPTION
**Pull request by kdimak**
When the input VC document has the same `id` of two fields, output BBS+ Signature Proof of VC (selective disclosure) may contain invalid substituted fields.

The issue is filed in json-gold library ([link](https://github.com/piprate/json-gold/issues/44)). It works properly at JSON-LD playground ([link](https://tinyurl.com/y3ypdrcj)). So current PR provides a workaround solution - to replace duplicated IDs with generated unique IDs before JSON-LD framing and then replacing IDs back.

closes #2460

Signed-off-by: Dmitriy Kinoshenko <dkinoshenko@gmail.com>

### CODE REVIEW

File: pkg/doc/verifiable/example_credential_test.go [hunk 1]
```diff
@@ -484,7 +484,7 @@ func ExampleCredential_GenerateBBSSelectiveDisclosure() {
 	   "VerifiableCredential",
 	   "PermanentResidentCard"
 	 ],
-	 "issuer": "did:example:489398593",
+	 "issuer": "did:example:b34ca6cd37bbf23",
```
Comment (kdimak) [inline pkg/doc/verifiable/example_credential_test.go:487]: Here we use `did:example:b34ca6cd37bbf23` ID for the `issuer` what coincides with ID of `credentialSubject`.

File: pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go [hunk 2]
```diff
@@ -192,19 +192,7 @@ func buildDocVerificationData(docCompacted, revealDoc map[string]interface{},
 		return nil, fmt.Errorf("create verify document data: %w", err)
 	}
 
-	transformedInputDocumentStatements := make([]string, len(documentStatements))
```
Comment (kdimak) [inline pkg/doc/signature/suite/bbsblssignatureproof2020/signer.go:195]: This code was redundant.

**Review by fqutishat — APPROVED** [review]

**Review by Baha-sk — APPROVED** [review]
